In [ ]:
import pandas as pd

# 1. Creación de series y dataframes

In [ ]:
a = [34, 78, 22, 13]

In [ ]:
type(a)

list

In [ ]:
mi_serie = pd.Series(a)

In [ ]:
mi_serie

0    34
1    78
2    22
3    13
dtype: int64

In [ ]:
type(mi_serie)

pandas.core.series.Series

In [ ]:
data = {
    "calorias": [420, 380, 390],
    "duracion": [50, 40, 45]
}

In [ ]:
type(data)

dict

In [ ]:
mi_dataframe = pd.DataFrame(data)

In [ ]:
mi_dataframe

   calorias  duracion
0       420        50
1       380        40
2       390        45

In [ ]:
df_prueba = pd.DataFrame()

In [ ]:
df_prueba['edad'] = [12, 20, 14, 18]

In [ ]:
df_prueba

   edad
0    12
1    20
2    14
3    18

In [ ]:
df_prueba["peso"] = [56, 62, 74, 58]

In [ ]:
df_prueba

   edad  peso
0    12    56
1    20    62
2    14    74
3    18    58

#2. Lectura de archivos csv y excel

Datasets: Alumnos matriculados en la Universidad Nacional de Ingeniería 2024-2 al 2025-1 [UNI]

https://www.datosabiertos.gob.pe/dataset/alumnos-matriculados-en-la-universidad-nacional-de-ingenier%C3%ADa-2024-2-al-2025-1-uni

In [ ]:
df_alumnos_uni = pd.read_csv("/content/Datos_abiertos_matriculas_2024_2_2025_1_0.csv", sep=',')

In [ ]:
df_alumnos_uni

,IDHASH,COLEGIO_DEPA,COLEGIO_PROV,COLEGIO_DIST,ANIO,PERIODO,TIPO_MATRICULA,DOMICILIO_DEPA,DOMICILIO_PROV,DOMICILIO_DIST,...,NACIMIENTO_DEPA,NACIMIENTO_PROV,NACIMIENTO_DIST,SEXO,MODALIDAD,METODOLOGIA,FACULTAD,ESPECIALIDAD,CICLO_RELATIVO,FECHA_CORTE
0,04411BA6C8D0AC65DA30537077ED135906545B6ED5A828...,LIMA,LIMA METROPOLITANA,VILLA MARIA DEL TRIUNFO,2024,2,REINCORPORADOS,LIMA,LIMA METROPOLITANA,VILLA MARIA DEL TRIUNFO,...,LIMA,LIMA METROPOLITANA,VILLA MARIA DEL TRIUNFO,MASCULINO,PREGRADO,PRESENCIAL,CIENCIAS,FÍSICA,10,20250630
1,B75E8796ADEEDB529C46058DA951BB17D1CCF2E2EB5B43...,LIMA,LIMA METROPOLITANA,VILLA EL SALVADOR,2024,2,REGULARES,LIMA,LIMA METROPOLITANA,SAN JUAN DE MIRAFLORES,...,LIMA,LIMA METROPOLITANA,SAN JUAN DE MIRAFLORES,MASCULINO,PREGRADO,PRESENCIAL,INGENIERÍA AMBIENTAL,INGENIERÍA AMBIENTAL,11,20250630
2,126C073D64AFB15EDA6003208FE900EFFA3D61C5464F84...,JUNIN,TARMA,SAN PEDRO DE CAJAS,2024,2,REGULARES,JUNIN,TARMA,SAN PEDRO DE CAJAS,...,JUNIN,TARMA,SAN PEDRO DE CAJAS,MASCULINO,PREGRADO,PRESENCIAL,"INGENIERÍA GEOLÓGICA, MINERA Y METALÚRGICA",INGENIERÍA DE MINAS,11,20250630
3,8AB39A3758E64121E67D0E7FD202C5A00B70AD544002AC...,LIMA,LIMA METROPOLITANA,LA VICTORIA,2024,2,REGULARES,LIMA,LIMA METROPOLITANA,LA VICTORIA,...,LIMA,LIMA METROPOLITANA,LA VICTORIA,MASCULINO,PREGRADO,PRESENCIAL,INGENIERÍA AMBIENTAL,INGENIERÍA SANITARIA,11,20250630
4,8E04C32C034E11F5523A88045E2ADE0F157D5BFB9C37EF...,CALLAO,CALLAO,VENTANILLA,2024,2,REGULARES,CALLAO,CALLAO,VENTANILLA,...,LIMA,LIMA METROPOLITANA,PUENTE PIEDRA,MASCULINO,PREGRADO,PRESENCIAL,INGENIERÍA INDUSTRIAL Y DE SISTEMAS,INGENIERÍA DE SOFTWARE,2,20250630
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24877,73074978180611CC8B9D40523BF4C286A7194742DE75E7...,LIMA,LIMA METROPOLITANA,CARABAYLLO,2025,1,REGULARES,LIMA,LIMA METROPOLITANA,COMAS,...,LIMA,LIMA METROPOLITANA,JESUS MARIA,MASCULINO,PREGRADO,PRESENCIAL,INGENIERÍA CIVIL,INGENIERÍA CIVIL,11,20250630
24878,F7819AD164959E40AE05A76C7150AE8D25B0575894E69A...,LIMA,LIMA METROPOLITANA,PUENTE PIEDRA,2025,1,REGULARES,LIMA,LIMA METROPOLITANA,PUENTE PIEDRA,...,LIMA,LIMA METROPOLITANA,PUENTE PIEDRA,FEMENINO,PREGRADO,PRESENCIAL,CIENCIAS,QUÍMICA,6,20250630
24879,D5A4E7716907039C1BC35B7ADFC7F15098854A25F2511A...,LIMA,LIMA METROPOLITANA,LOS OLIVOS,2025,1,REGULARES,LIMA,LIMA METROPOLITANA,SAN MIGUEL,...,LIMA,LIMA METROPOLITANA,MIRAFLORES,MASCULINO,PREGRADO,PRESENCIAL,INGENIERÍA INDUSTRIAL Y DE SISTEMAS,INGENIERÍA DE SISTEMAS,2,20250630
24880,4F19DD51DA3C2869BFC04D11352E96D6FD942B71DF9F57...,LIMA,CAÑETE,SAN VICENTE DE CAÑETE,2025,1,REGULARES,LIMA,CAÑETE,SAN VICENTE DE CAÑETE,...,LIMA,CAÑETE,SAN VICENTE DE CAÑETE,MASCULINO,PREGRADO,PRESENCIAL,INGENIERÍA AMBIENTAL,INGENIERÍA DE HIGIENE Y SEGURIDAD INDUSTRIAL,2,20250630
24881,BE93E75EA31505FD2E2585A38023D7973D80B8556FC097...,LIMA,LIMA METROPOLITANA,COMAS,2025,1,REGULARES,LIMA,LIMA METROPOLITANA,CARABAYLLO,...,LIMA,LIMA METROPOLITANA,CARABAYLLO,MASCULINO,PREGRADO,PRESENCIAL,INGENIERÍA MECÁNICA,INGENIERÍA MECATRÓNICA,1,20250630

In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df_alumnos_uni_2 = pd.read_csv("/content/drive/MyDrive/data_curso_python/Datos_abiertos_matriculas_2024_2_2025_1_0.csv", sep=',')

In [ ]:
df_alumnos_uni_2

,IDHASH,COLEGIO_DEPA,COLEGIO_PROV,COLEGIO_DIST,ANIO,PERIODO,TIPO_MATRICULA,DOMICILIO_DEPA,DOMICILIO_PROV,DOMICILIO_DIST,...,NACIMIENTO_DEPA,NACIMIENTO_PROV,NACIMIENTO_DIST,SEXO,MODALIDAD,METODOLOGIA,FACULTAD,ESPECIALIDAD,CICLO_RELATIVO,FECHA_CORTE
0,04411BA6C8D0AC65DA30537077ED135906545B6ED5A828...,LIMA,LIMA METROPOLITANA,VILLA MARIA DEL TRIUNFO,2024,2,REINCORPORADOS,LIMA,LIMA METROPOLITANA,VILLA MARIA DEL TRIUNFO,...,LIMA,LIMA METROPOLITANA,VILLA MARIA DEL TRIUNFO,MASCULINO,PREGRADO,PRESENCIAL,CIENCIAS,FÍSICA,10,20250630
1,B75E8796ADEEDB529C46058DA951BB17D1CCF2E2EB5B43...,LIMA,LIMA METROPOLITANA,VILLA EL SALVADOR,2024,2,REGULARES,LIMA,LIMA METROPOLITANA,SAN JUAN DE MIRAFLORES,...,LIMA,LIMA METROPOLITANA,SAN JUAN DE MIRAFLORES,MASCULINO,PREGRADO,PRESENCIAL,INGENIERÍA AMBIENTAL,INGENIERÍA AMBIENTAL,11,20250630
2,126C073D64AFB15EDA6003208FE900EFFA3D61C5464F84...,JUNIN,TARMA,SAN PEDRO DE CAJAS,2024,2,REGULARES,JUNIN,TARMA,SAN PEDRO DE CAJAS,...,JUNIN,TARMA,SAN PEDRO DE CAJAS,MASCULINO,PREGRADO,PRESENCIAL,"INGENIERÍA GEOLÓGICA, MINERA Y METALÚRGICA",INGENIERÍA DE MINAS,11,20250630
3,8AB39A3758E64121E67D0E7FD202C5A00B70AD544002AC...,LIMA,LIMA METROPOLITANA,LA VICTORIA,2024,2,REGULARES,LIMA,LIMA METROPOLITANA,LA VICTORIA,...,LIMA,LIMA METROPOLITANA,LA VICTORIA,MASCULINO,PREGRADO,PRESENCIAL,INGENIERÍA AMBIENTAL,INGENIERÍA SANITARIA,11,20250630
4,8E04C32C034E11F5523A88045E2ADE0F157D5BFB9C37EF...,CALLAO,CALLAO,VENTANILLA,2024,2,REGULARES,CALLAO,CALLAO,VENTANILLA,...,LIMA,LIMA METROPOLITANA,PUENTE PIEDRA,MASCULINO,PREGRADO,PRESENCIAL,INGENIERÍA INDUSTRIAL Y DE SISTEMAS,INGENIERÍA DE SOFTWARE,2,20250630
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24877,73074978180611CC8B9D40523BF4C286A7194742DE75E7...,LIMA,LIMA METROPOLITANA,CARABAYLLO,2025,1,REGULARES,LIMA,LIMA METROPOLITANA,COMAS,...,LIMA,LIMA METROPOLITANA,JESUS MARIA,MASCULINO,PREGRADO,PRESENCIAL,INGENIERÍA CIVIL,INGENIERÍA CIVIL,11,20250630
24878,F7819AD164959E40AE05A76C7150AE8D25B0575894E69A...,LIMA,LIMA METROPOLITANA,PUENTE PIEDRA,2025,1,REGULARES,LIMA,LIMA METROPOLITANA,PUENTE PIEDRA,...,LIMA,LIMA METROPOLITANA,PUENTE PIEDRA,FEMENINO,PREGRADO,PRESENCIAL,CIENCIAS,QUÍMICA,6,20250630
24879,D5A4E7716907039C1BC35B7ADFC7F15098854A25F2511A...,LIMA,LIMA METROPOLITANA,LOS OLIVOS,2025,1,REGULARES,LIMA,LIMA METROPOLITANA,SAN MIGUEL,...,LIMA,LIMA METROPOLITANA,MIRAFLORES,MASCULINO,PREGRADO,PRESENCIAL,INGENIERÍA INDUSTRIAL Y DE SISTEMAS,INGENIERÍA DE SISTEMAS,2,20250630
24880,4F19DD51DA3C2869BFC04D11352E96D6FD942B71DF9F57...,LIMA,CAÑETE,SAN VICENTE DE CAÑETE,2025,1,REGULARES,LIMA,CAÑETE,SAN VICENTE DE CAÑETE,...,LIMA,CAÑETE,SAN VICENTE DE CAÑETE,MASCULINO,PREGRADO,PRESENCIAL,INGENIERÍA AMBIENTAL,INGENIERÍA DE HIGIENE Y SEGURIDAD INDUSTRIAL,2,20250630
24881,BE93E75EA31505FD2E2585A38023D7973D80B8556FC097...,LIMA,LIMA METROPOLITANA,COMAS,2025,1,REGULARES,LIMA,LIMA METROPOLITANA,CARABAYLLO,...,LIMA,LIMA METROPOLITANA,CARABAYLLO,MASCULINO,PREGRADO,PRESENCIAL,INGENIERÍA MECÁNICA,INGENIERÍA MECATRÓNICA,1,20250630

In [ ]:
df_alumnos_uni_2.head()

,IDHASH,COLEGIO_DEPA,COLEGIO_PROV,COLEGIO_DIST,ANIO,PERIODO,TIPO_MATRICULA,DOMICILIO_DEPA,DOMICILIO_PROV,DOMICILIO_DIST,...,NACIMIENTO_DEPA,NACIMIENTO_PROV,NACIMIENTO_DIST,SEXO,MODALIDAD,METODOLOGIA,FACULTAD,ESPECIALIDAD,CICLO_RELATIVO,FECHA_CORTE
0,04411BA6C8D0AC65DA30537077ED135906545B6ED5A828...,LIMA,LIMA METROPOLITANA,VILLA MARIA DEL TRIUNFO,2024,2,REINCORPORADOS,LIMA,LIMA METROPOLITANA,VILLA MARIA DEL TRIUNFO,...,LIMA,LIMA METROPOLITANA,VILLA MARIA DEL TRIUNFO,MASCULINO,PREGRADO,PRESENCIAL,CIENCIAS,FÍSICA,10,20250630
1,B75E8796ADEEDB529C46058DA951BB17D1CCF2E2EB5B43...,LIMA,LIMA METROPOLITANA,VILLA EL SALVADOR,2024,2,REGULARES,LIMA,LIMA METROPOLITANA,SAN JUAN DE MIRAFLORES,...,LIMA,LIMA METROPOLITANA,SAN JUAN DE MIRAFLORES,MASCULINO,PREGRADO,PRESENCIAL,INGENIERÍA AMBIENTAL,INGENIERÍA AMBIENTAL,11,20250630
2,126C073D64AFB15EDA6003208FE900EFFA3D61C5464F84...,JUNIN,TARMA,SAN PEDRO DE CAJAS,2024,2,REGULARES,JUNIN,TARMA,SAN PEDRO DE CAJAS,...,JUNIN,TARMA,SAN PEDRO DE CAJAS,MASCULINO,PREGRADO,PRESENCIAL,"INGENIERÍA GEOLÓGICA, MINERA Y METALÚRGICA",INGENIERÍA DE MINAS,11,20250630
3,8AB39A3758E64121E67D0E7FD202C5A00B70AD544002AC...,LIMA,LIMA METROPOLITANA,LA VICTORIA,2024,2,REGULARES,LIMA,LIMA METROPOLITANA,LA VICTORIA,...,LIMA,LIMA METROPOLITANA,LA VICTORIA,MASCULINO,PREGRADO,PRESENCIAL,INGENIERÍA AMBIENTAL,INGENIERÍA SANITARIA,11,20250630
4,8E04C32C034E11F5523A88045E2ADE0F157D5BFB9C37EF...,CALLAO,CALLAO,VENTANILLA,2024,2,REGULARES,CALLAO,CALLAO,VENTANILLA,...,LIMA,LIMA METROPOLITANA,PUENTE PIEDRA,MASCULINO,PREGRADO,PRESENCIAL,INGENIERÍA INDUSTRIAL Y DE SISTEMAS,INGENIERÍA DE SOFTWARE,2,20250630

In [ ]:
df_alumnos_uni_2.shape

(24882, 22)

In [ ]:
df_alumnos_uni_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24882 entries, 0 to 24881
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   IDHASH           24882 non-null  object
 1   COLEGIO_DEPA     24882 non-null  object
 2   COLEGIO_PROV     24882 non-null  object
 3   COLEGIO_DIST     24882 non-null  object
 4   ANIO             24882 non-null  int64
 5   PERIODO          24882 non-null  int64
 6   TIPO_MATRICULA   24882 non-null  object
 7   DOMICILIO_DEPA   24882 non-null  object
 8   DOMICILIO_PROV   24882 non-null  object
 9   DOMICILIO_DIST   24882 non-null  object
 10  ANIO_NACIMIENTO  24882 non-null  int64
 11  NACIMIENTO_PAIS  24882 non-null  object
 12  NACIMIENTO_DEPA  24882 non-null  object
 13  NACIMIENTO_PROV  24882 non-null  object
 14  NACIMIENTO_DIST  24882 non-null  object
 15  SEXO             24882 non-null  object
 16  MODALIDAD        24882 non-null  object
 17  METODOLOGIA      24882 non-null  object
 18  FACULTAD         24882 non-null  object
 19  ESPECIALIDAD     24882 non-null  object
 20  CICLO_RELATIVO   24882 non-null  int64
 21  FECHA_CORTE      24882 non-null  int64
dtypes: int64(5), object(17)
memory usage: 4.2+ MB

In [ ]:
df_diccionario = pd.read_excel("/content/drive/MyDrive/data_curso_python/DiccionarioDatos_matriculados.xlsx", header=3)

In [ ]:
df_diccionario

,Columnas,Descripción,Tipo de dato,Tamaño,RECURSOS RELACIONADOS,Informacion adicional
0,IDHASH,"Identificador anónimo único para cada alumno, ...",Alfanumérico,128.0,NaN,54CB3E...B25FC9
1,COLEGIO_DEPA,Departamento donde se encuentra ubicado el col...,texto,20.0,Catálogo del INEI,NaN
2,COLEGIO_PROV,Provincia donde se encuentra ubicado el colegi...,texto,50.0,Catálogo del INEI,NaN
3,COLEGIO_DIST,Distrito donde se encuentra ubicado el colegio...,texto,50.0,Catálogo del INEI,NaN
4,ANIO,Año en que se matricula el alumno,numérico,4.0,NaN,Formato: aaaa
5,PERIODO,Ciclo del año en que matricula el alumno,numérico,1.0,NaN,NaN
6,TIPO_MATRICULA,"Tipo de matrícula para el alumno: Regulares, ...",NaN,NaN,NaN,NaN
7,DOMICILIO_DEPA,Departamento donde se encuentra ubicado el dom...,texto,20.0,Catálogo del INEI,NaN
8,DOMICILIO_PROV,Provincia donde se encuentra ubicado el domici...,texto,50.0,Catálogo del INEI,NaN
9,DOMICILIO_DIST,Distrito donde se encuentra ubicado el domicil...,texto,50.0,Catálogo del INEI,NaN
10,ANIO_NACIMIENTO,Año de nacimiento del alumno,numérico,4.0,NaN,Formato: aaaa
11,NACIMIENTO_PAIS,Nombre del pais de nacimiento del alumno,texto,50.0,NaN,NaN
12,NACIMIENTO_DEPA,Departamento donde se encuentra ubicado el lug...,texto,20.0,Catálogo del INEI,NaN
13,NACIMIENTO_PROV,Provincia donde se encuentra ubicado el lugar ...,texto,50.0,Catálogo del INEI,NaN
14,NACIMIENTO_DIST,Distrito donde se encuentra ubicado el lugar d...,texto,50.0,Catálogo del INEI,NaN
15,SEXO,"Sexo del alumno a la universidad: MASCULINO, F...",texto,10.0,NaN,NaN
16,MODALIDAD,"Modalidad de ingreso: ORDINARIO, INGRESO DIREC...",texto,100.0,NaN,NaN
17,METODOLOGIA,Indica si las clases se realizan de manera pre...,texto,100.0,NaN,NaN
18,FACULTAD,Nombre de la facultad,texto,150.0,NaN,NaN
19,ESPECIALIDAD,Nombre de la especialidad profesional a la que...,texto,150.0,NaN,NaN
20,CICLO_RELATIVO,"Avance periódico, su valor es entre 1 y 11",numérico,1.0,NaN,NaN

# 3. Guardar dataframes en archivos csv

In [ ]:
df_prueba

   edad  peso
0    12    56
1    20    62
2    14    74
3    18    58

In [ ]:
df_prueba.to_csv("/content/drive/MyDrive/data_curso_python/data_prueba_2026.csv", index=False)

#4. Selección de columnas

In [ ]:
df_alumnos_uni_2[['IDHASH', 'COLEGIO_DEPA', 'COLEGIO_PROV', 'COLEGIO_DIST']]

,IDHASH,COLEGIO_DEPA,COLEGIO_PROV,COLEGIO_DIST
0,04411BA6C8D0AC65DA30537077ED135906545B6ED5A828...,LIMA,LIMA METROPOLITANA,VILLA MARIA DEL TRIUNFO
1,B75E8796ADEEDB529C46058DA951BB17D1CCF2E2EB5B43...,LIMA,LIMA METROPOLITANA,VILLA EL SALVADOR
2,126C073D64AFB15EDA6003208FE900EFFA3D61C5464F84...,JUNIN,TARMA,SAN PEDRO DE CAJAS
3,8AB39A3758E64121E67D0E7FD202C5A00B70AD544002AC...,LIMA,LIMA METROPOLITANA,LA VICTORIA
4,8E04C32C034E11F5523A88045E2ADE0F157D5BFB9C37EF...,CALLAO,CALLAO,VENTANILLA
...,...,...,...,...
24877,73074978180611CC8B9D40523BF4C286A7194742DE75E7...,LIMA,LIMA METROPOLITANA,CARABAYLLO
24878,F7819AD164959E40AE05A76C7150AE8D25B0575894E69A...,LIMA,LIMA METROPOLITANA,PUENTE PIEDRA
24879,D5A4E7716907039C1BC35B7ADFC7F15098854A25F2511A...,LIMA,LIMA METROPOLITANA,LOS OLIVOS
24880,4F19DD51DA3C2869BFC04D11352E96D6FD942B71DF9F57...,LIMA,CAÑETE,SAN VICENTE DE CAÑETE
24881,BE93E75EA31505FD2E2585A38023D7973D80B8556FC097...,LIMA,LIMA METROPOLITANA,COMAS

In [ ]:
df_alumnos_uni_2.filter(['IDHASH', 'COLEGIO_DEPA', 'COLEGIO_PROV', 'COLEGIO_DIST', 'ANIO', 	'PERIODO'])

,IDHASH,COLEGIO_DEPA,COLEGIO_PROV,COLEGIO_DIST,ANIO,PERIODO
0,04411BA6C8D0AC65DA30537077ED135906545B6ED5A828...,LIMA,LIMA METROPOLITANA,VILLA MARIA DEL TRIUNFO,2024,2
1,B75E8796ADEEDB529C46058DA951BB17D1CCF2E2EB5B43...,LIMA,LIMA METROPOLITANA,VILLA EL SALVADOR,2024,2
2,126C073D64AFB15EDA6003208FE900EFFA3D61C5464F84...,JUNIN,TARMA,SAN PEDRO DE CAJAS,2024,2
3,8AB39A3758E64121E67D0E7FD202C5A00B70AD544002AC...,LIMA,LIMA METROPOLITANA,LA VICTORIA,2024,2
4,8E04C32C034E11F5523A88045E2ADE0F157D5BFB9C37EF...,CALLAO,CALLAO,VENTANILLA,2024,2
...,...,...,...,...,...,...
24877,73074978180611CC8B9D40523BF4C286A7194742DE75E7...,LIMA,LIMA METROPOLITANA,CARABAYLLO,2025,1
24878,F7819AD164959E40AE05A76C7150AE8D25B0575894E69A...,LIMA,LIMA METROPOLITANA,PUENTE PIEDRA,2025,1
24879,D5A4E7716907039C1BC35B7ADFC7F15098854A25F2511A...,LIMA,LIMA METROPOLITANA,LOS OLIVOS,2025,1
24880,4F19DD51DA3C2869BFC04D11352E96D6FD942B71DF9F57...,LIMA,CAÑETE,SAN VICENTE DE CAÑETE,2025,1
24881,BE93E75EA31505FD2E2585A38023D7973D80B8556FC097...,LIMA,LIMA METROPOLITANA,COMAS,2025,1

#5. Selección de filas

## 5.1. Por valor

In [ ]:
df_alumnos_uni_2.loc[df_alumnos_uni_2["COLEGIO_DEPA"].isin(["JUNIN", "PASCO"])]

,IDHASH,COLEGIO_DEPA,COLEGIO_PROV,COLEGIO_DIST,ANIO,PERIODO,TIPO_MATRICULA,DOMICILIO_DEPA,DOMICILIO_PROV,DOMICILIO_DIST,...,NACIMIENTO_DEPA,NACIMIENTO_PROV,NACIMIENTO_DIST,SEXO,MODALIDAD,METODOLOGIA,FACULTAD,ESPECIALIDAD,CICLO_RELATIVO,FECHA_CORTE
2,126C073D64AFB15EDA6003208FE900EFFA3D61C5464F84...,JUNIN,TARMA,SAN PEDRO DE CAJAS,2024,2,REGULARES,JUNIN,TARMA,SAN PEDRO DE CAJAS,...,JUNIN,TARMA,SAN PEDRO DE CAJAS,MASCULINO,PREGRADO,PRESENCIAL,"INGENIERÍA GEOLÓGICA, MINERA Y METALÚRGICA",INGENIERÍA DE MINAS,11,20250630
45,576C74C6B23B2EE98230A8D600188F352699AC5E78A209...,PASCO,OXAPAMPA,YANACANCHA,2024,2,PROMOCION,PASCO,OXAPAMPA,CHAUPIMARCA,...,PASCO,OXAPAMPA,CHAUPIMARCA,MASCULINO,PREGRADO,PRESENCIAL,INGENIERÍA MECÁNICA,INGENIERÍA MECÁNICA,10,20250630
54,7473ADC75FDEC0DABC9883BBEC82EC2F2BA06E020C3157...,JUNIN,SATIPO,MAZAMARI,2024,2,REGULARES,LIMA,LIMA METROPOLITANA,CARABAYLLO,...,LIMA,LIMA METROPOLITANA,CARABAYLLO,MASCULINO,PREGRADO,PRESENCIAL,INGENIERÍA INDUSTRIAL Y DE SISTEMAS,INGENIERÍA DE SISTEMAS,2,20250630
96,574C9E0A35194EF6CAC99C73E56E81A9273518FB1345EA...,JUNIN,HUANCAYO,HUANCAYO,2024,2,REGULARES,LIMA,LIMA METROPOLITANA,SAN MARTIN DE PORRES,...,JUNIN,HUANCAYO,HUANCAYO,FEMENINO,PREGRADO,PRESENCIAL,CIENCIAS,INGENIERÍA FÍSICA,6,20250630
105,FA1BA835B4566E69E12B4B685B4BE2BF3AB8F49A2CD8A5...,JUNIN,HUANCAYO,SAN JERONIMO DE TUNAN,2024,2,REGULARES,AMAZONAS,NO INDICA,NO INDICA,...,JUNIN,HUANCAYO,PUCARA,FEMENINO,PREGRADO,PRESENCIAL,INGENIERÍA AMBIENTAL,INGENIERÍA SANITARIA,11,20250630
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24763,26A2F66034BF32AAE988E396A2FF4A12DA2A618EB92AF6...,JUNIN,HUANCAYO,HUANCAYO,2025,1,REGULARES,JUNIN,HUANCAYO,HUANCAN,...,JUNIN,HUANCAYO,HUANCAYO,MASCULINO,PREGRADO,PRESENCIAL,"INGENIERÍA ECONÓMICA, ESTADÍSTICA Y CIENCIAS S...",INGENIERÍA ECONÓMICA,4,20250630
24765,80B893DC64DD02ED84BD0A68165C1148C5AE5CE1525D78...,JUNIN,TARMA,TARMA,2025,1,RIESGO ACADEMICO,LIMA,LIMA METROPOLITANA,LURIGANCHO,...,JUNIN,TARMA,TARMA,MASCULINO,PREGRADO,PRESENCIAL,INGENIERÍA CIVIL,INGENIERÍA CIVIL,4,20250630
24812,C9A1833C010F2AF6DD890D3D5ECE283E64BCC55C7F1D20...,JUNIN,YAULI,LA OROYA,2025,1,REGULARES,LIMA,LIMA METROPOLITANA,ATE,...,JUNIN,YAULI,LA OROYA,MASCULINO,PREGRADO,PRESENCIAL,INGENIERÍA MECÁNICA,INGENIERÍA MECATRÓNICA,8,20250630
24817,ACDFE47CBE84B0D7A36B9B5483DE723B13B5167C1302BB...,JUNIN,YAULI,LA OROYA,2025,1,REGULARES,LIMA,LIMA METROPOLITANA,SAN JUAN DE LURIGANCHO,...,JUNIN,YAULI,LA OROYA,MASCULINO,PREGRADO,PRESENCIAL,INGENIERÍA QUÍMICA Y TEXTIL,INGENIERÍA QUÍMICA,10,20250630
24863,C604DBD625F762FFB6D3D678DCC3D5785F4E8CAD0D0F40...,JUNIN,HUANCAYO,HUANCAYO,2025,1,REGULARES,LIMA,LIMA METROPOLITANA,SAN JUAN DE LURIGANCHO,...,JUNIN,HUANCAYO,EL TAMBO,MASCULINO,PREGRADO,PRESENCIAL,INGENIERÍA MECÁNICA,INGENIERÍA MECATRÓNICA,1,20250630

In [ ]:
df_alumnos_uni_2.loc[df_alumnos_uni_2["COLEGIO_DEPA"]=="JUNIN"]

,IDHASH,COLEGIO_DEPA,COLEGIO_PROV,COLEGIO_DIST,ANIO,PERIODO,TIPO_MATRICULA,DOMICILIO_DEPA,DOMICILIO_PROV,DOMICILIO_DIST,...,NACIMIENTO_DEPA,NACIMIENTO_PROV,NACIMIENTO_DIST,SEXO,MODALIDAD,METODOLOGIA,FACULTAD,ESPECIALIDAD,CICLO_RELATIVO,FECHA_CORTE
2,126C073D64AFB15EDA6003208FE900EFFA3D61C5464F84...,JUNIN,TARMA,SAN PEDRO DE CAJAS,2024,2,REGULARES,JUNIN,TARMA,SAN PEDRO DE CAJAS,...,JUNIN,TARMA,SAN PEDRO DE CAJAS,MASCULINO,PREGRADO,PRESENCIAL,"INGENIERÍA GEOLÓGICA, MINERA Y METALÚRGICA",INGENIERÍA DE MINAS,11,20250630
54,7473ADC75FDEC0DABC9883BBEC82EC2F2BA06E020C3157...,JUNIN,SATIPO,MAZAMARI,2024,2,REGULARES,LIMA,LIMA METROPOLITANA,CARABAYLLO,...,LIMA,LIMA METROPOLITANA,CARABAYLLO,MASCULINO,PREGRADO,PRESENCIAL,INGENIERÍA INDUSTRIAL Y DE SISTEMAS,INGENIERÍA DE SISTEMAS,2,20250630
96,574C9E0A35194EF6CAC99C73E56E81A9273518FB1345EA...,JUNIN,HUANCAYO,HUANCAYO,2024,2,REGULARES,LIMA,LIMA METROPOLITANA,SAN MARTIN DE PORRES,...,JUNIN,HUANCAYO,HUANCAYO,FEMENINO,PREGRADO,PRESENCIAL,CIENCIAS,INGENIERÍA FÍSICA,6,20250630
105,FA1BA835B4566E69E12B4B685B4BE2BF3AB8F49A2CD8A5...,JUNIN,HUANCAYO,SAN JERONIMO DE TUNAN,2024,2,REGULARES,AMAZONAS,NO INDICA,NO INDICA,...,JUNIN,HUANCAYO,PUCARA,FEMENINO,PREGRADO,PRESENCIAL,INGENIERÍA AMBIENTAL,INGENIERÍA SANITARIA,11,20250630
194,1ADA21B76E05EA036E1825CC7BD71B08F3E46B9A716A97...,JUNIN,TARMA,HUASAHUASI,2024,2,PROMOCION,LIMA,LIMA METROPOLITANA,SAN MARTIN DE PORRES,...,JUNIN,TARMA,HUASAHUASI,MASCULINO,PREGRADO,PRESENCIAL,"INGENIERÍA ECONÓMICA, ESTADÍSTICA Y CIENCIAS S...",INGENIERÍA ECONÓMICA,10,20250630
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24763,26A2F66034BF32AAE988E396A2FF4A12DA2A618EB92AF6...,JUNIN,HUANCAYO,HUANCAYO,2025,1,REGULARES,JUNIN,HUANCAYO,HUANCAN,...,JUNIN,HUANCAYO,HUANCAYO,MASCULINO,PREGRADO,PRESENCIAL,"INGENIERÍA ECONÓMICA, ESTADÍSTICA Y CIENCIAS S...",INGENIERÍA ECONÓMICA,4,20250630
24765,80B893DC64DD02ED84BD0A68165C1148C5AE5CE1525D78...,JUNIN,TARMA,TARMA,2025,1,RIESGO ACADEMICO,LIMA,LIMA METROPOLITANA,LURIGANCHO,...,JUNIN,TARMA,TARMA,MASCULINO,PREGRADO,PRESENCIAL,INGENIERÍA CIVIL,INGENIERÍA CIVIL,4,20250630
24812,C9A1833C010F2AF6DD890D3D5ECE283E64BCC55C7F1D20...,JUNIN,YAULI,LA OROYA,2025,1,REGULARES,LIMA,LIMA METROPOLITANA,ATE,...,JUNIN,YAULI,LA OROYA,MASCULINO,PREGRADO,PRESENCIAL,INGENIERÍA MECÁNICA,INGENIERÍA MECATRÓNICA,8,20250630
24817,ACDFE47CBE84B0D7A36B9B5483DE723B13B5167C1302BB...,JUNIN,YAULI,LA OROYA,2025,1,REGULARES,LIMA,LIMA METROPOLITANA,SAN JUAN DE LURIGANCHO,...,JUNIN,YAULI,LA OROYA,MASCULINO,PREGRADO,PRESENCIAL,INGENIERÍA QUÍMICA Y TEXTIL,INGENIERÍA QUÍMICA,10,20250630
24863,C604DBD625F762FFB6D3D678DCC3D5785F4E8CAD0D0F40...,JUNIN,HUANCAYO,HUANCAYO,2025,1,REGULARES,LIMA,LIMA METROPOLITANA,SAN JUAN DE LURIGANCHO,...,JUNIN,HUANCAYO,EL TAMBO,MASCULINO,PREGRADO,PRESENCIAL,INGENIERÍA MECÁNICA,INGENIERÍA MECATRÓNICA,1,20250630

## 5.2. Por índice

In [ ]:
df_alumnos_uni_2.iloc[0:25]

,IDHASH,COLEGIO_DEPA,COLEGIO_PROV,COLEGIO_DIST,ANIO,PERIODO,TIPO_MATRICULA,DOMICILIO_DEPA,DOMICILIO_PROV,DOMICILIO_DIST,...,NACIMIENTO_DEPA,NACIMIENTO_PROV,NACIMIENTO_DIST,SEXO,MODALIDAD,METODOLOGIA,FACULTAD,ESPECIALIDAD,CICLO_RELATIVO,FECHA_CORTE
0,04411BA6C8D0AC65DA30537077ED135906545B6ED5A828...,LIMA,LIMA METROPOLITANA,VILLA MARIA DEL TRIUNFO,2024,2,REINCORPORADOS,LIMA,LIMA METROPOLITANA,VILLA MARIA DEL TRIUNFO,...,LIMA,LIMA METROPOLITANA,VILLA MARIA DEL TRIUNFO,MASCULINO,PREGRADO,PRESENCIAL,CIENCIAS,FÍSICA,10,20250630
1,B75E8796ADEEDB529C46058DA951BB17D1CCF2E2EB5B43...,LIMA,LIMA METROPOLITANA,VILLA EL SALVADOR,2024,2,REGULARES,LIMA,LIMA METROPOLITANA,SAN JUAN DE MIRAFLORES,...,LIMA,LIMA METROPOLITANA,SAN JUAN DE MIRAFLORES,MASCULINO,PREGRADO,PRESENCIAL,INGENIERÍA AMBIENTAL,INGENIERÍA AMBIENTAL,11,20250630
2,126C073D64AFB15EDA6003208FE900EFFA3D61C5464F84...,JUNIN,TARMA,SAN PEDRO DE CAJAS,2024,2,REGULARES,JUNIN,TARMA,SAN PEDRO DE CAJAS,...,JUNIN,TARMA,SAN PEDRO DE CAJAS,MASCULINO,PREGRADO,PRESENCIAL,"INGENIERÍA GEOLÓGICA, MINERA Y METALÚRGICA",INGENIERÍA DE MINAS,11,20250630
3,8AB39A3758E64121E67D0E7FD202C5A00B70AD544002AC...,LIMA,LIMA METROPOLITANA,LA VICTORIA,2024,2,REGULARES,LIMA,LIMA METROPOLITANA,LA VICTORIA,...,LIMA,LIMA METROPOLITANA,LA VICTORIA,MASCULINO,PREGRADO,PRESENCIAL,INGENIERÍA AMBIENTAL,INGENIERÍA SANITARIA,11,20250630
4,8E04C32C034E11F5523A88045E2ADE0F157D5BFB9C37EF...,CALLAO,CALLAO,VENTANILLA,2024,2,REGULARES,CALLAO,CALLAO,VENTANILLA,...,LIMA,LIMA METROPOLITANA,PUENTE PIEDRA,MASCULINO,PREGRADO,PRESENCIAL,INGENIERÍA INDUSTRIAL Y DE SISTEMAS,INGENIERÍA DE SOFTWARE,2,20250630
5,5E7836E6726BEA39F0BAA2C77809A161ADDC5485BAE94C...,LIMA,LIMA METROPOLITANA,LOS OLIVOS,2024,2,REGULARES,LIMA,LIMA METROPOLITANA,LOS OLIVOS,...,HUANUCO,DOS DE MAYO,LA UNION,MASCULINO,PREGRADO,PRESENCIAL,INGENIERÍA MECÁNICA,INGENIERÍA MECÁNICA,10,20250630
6,E32002BF7325AE21736A48FBE7A673489718C2C6303DB9...,LIMA,LIMA METROPOLITANA,SAN MARTIN DE PORRES,2024,2,REGULARES,LIMA,LIMA METROPOLITANA,INDEPENDENCIA,...,LIMA,LIMA METROPOLITANA,INDEPENDENCIA,MASCULINO,PREGRADO,PRESENCIAL,INGENIERÍA AMBIENTAL,INGENIERÍA DE HIGIENE Y SEGURIDAD INDUSTRIAL,2,20250630
7,DB188F93931E5BBA3E7A3D7700E1A0DD72633B5D6B9D14...,LIMA,LIMA METROPOLITANA,LURIGANCHO,2024,2,REGULARES,LIMA,LIMA METROPOLITANA,ATE,...,LIMA,LIMA METROPOLITANA,SANTIAGO DE SURCO,MASCULINO,PREGRADO,PRESENCIAL,INGENIERÍA INDUSTRIAL Y DE SISTEMAS,INGENIERÍA DE SISTEMAS,2,20250630
8,CBD9D12FD085965FC409E05A8EA48142A39E59C9979A9D...,CALLAO,CALLAO,VENTANILLA,2024,2,REGULARES,CALLAO,CALLAO,VENTANILLA,...,LIMA,LIMA METROPOLITANA,LIMA,FEMENINO,PREGRADO,PRESENCIAL,INGENIERÍA AMBIENTAL,INGENIERÍA DE HIGIENE Y SEGURIDAD INDUSTRIAL,2,20250630
9,C4439C5CB18C984C4E12BCBBE5A21206A594230209F823...,LIMA,LIMA METROPOLITANA,SAN JUAN DE LURIGANCHO,2024,2,REGULARES,LIMA,LIMA METROPOLITANA,SAN JUAN DE LURIGANCHO,...,LIMA,LIMA METROPOLITANA,RIMAC,FEMENINO,PREGRADO,PRESENCIAL,INGENIERÍA AMBIENTAL,INGENIERÍA AMBIENTAL,2,20250630
10,41DBAB0CF1CE8511E1D207C9C5D79A3781FE4C397FA3AE...,HUANCAVELICA,HUANCAVELICA,HUANCAVELICA,2024,2,REINCORPORADOS,LIMA,LIMA METROPOLITANA,SAN MARTIN DE PORRES,...,HUANCAVELICA,HUANCAVELICA,HUANCAVELICA,MASCULINO,PREGRADO,PRESENCIAL,INGENIERÍA AMBIENTAL,INGENIERÍA AMBIENTAL,1,20250630
11,AF92AD6FA4B415EE46802721430D67C8953EB5B6AA6C8D...,NO INDICA,NO INDICA,NO INDICA,2024,2,REGULARES,LIMA,LIMA METROPOLITANA,LURIGANCHO,...,LIMA,LIMA METROPOLITANA,LURIGANCHO,FEMENINO,PREGRADO,PRESENCIAL,INGENIERÍA AMBIENTAL,INGENIERÍA AMBIENTAL,2,20250630
12,377785A55821F775AAB50D6EA79A8683B829C4142FE856...,LIMA,LIMA METROPOLITANA,SAN JUAN DE LURIGANCHO,2024,2,Cachimbos,LIMA,LIMA METROPOLITANA,SAN JUAN DE LURIGANCHO,...,LIMA,LIMA METROPOLITANA,SAN JUAN DE LURIGANCHO,MASCULINO,PREGRADO,PRESENCIAL,INGENIERÍA AMBIENTAL,INGENIERÍA SANITARIA,1,20250630
13,B4267AAF3CBD9BF1A55C318219EB42A2BD7C5D59447258...,LIMA,LIMA METROPOLITANA,CARABAYLLO,2024,2,REGULARES,LIMA,LIMA METROPOLITANA,CARABAYLLO,...,LIMA,LIMA METROPOLITANA,CARABAYLLO,MASCULINO,PREGRADO,PRESENCIAL,"INGENIERÍA DE PETRÓLEO, GAS NATURAL Y PETROQUÍ...",INGENIERÍA PETROQUÍMICA,6,20250630
14,8453B6F7E72158A9E7239E33422D516786808AA4374E21...,LIMA,LIMA METROPOLITANA,INDEPENDENCIA,2024,2,REGULARES,LIMA,LIMA METROPOLITANA,INDEPENDENCIA,...,LIMA,LIMA METROPOLITANA,INDEPENDENCIA,MASCULINO,PREGRADO,PRESENCIAL,"INGENIERÍA DE PETRÓLEO, GAS NATURAL Y PETROQUÍ...",INGENIERÍA PETROQUÍMICA,10,20250630
15,4380B7FB64F0BFB589F4719B040724359E6F11C4CA99F5...,LIMA,LIMA METROPOLITANA,LOS OLIVOS,2024,2,REGULARES,LIMA,LIMA METROPOLITANA,LOS OLIVOS,...,LIMA,LIMA METROPOLITANA,LOS OLIVOS,MASCULINO,PREGRADO,PRESENCIAL,"INGENIERÍA DE PETRÓLEO, GAS NATURAL Y PETROQUÍ...",INGENIERÍA PETROQUÍMICA,10,20250630
16,CEF68E098856EBDC048F1E498BCD39B18D6CB6BC5D1EF1...,LIMA,LIMA METROPOLITANA,LINCE,2024,2,REGULARES,LIMA,LIMA METROPOLITANA,LA VICTORIA,...,LIMA,LIMA METROPOLITANA,LA VICTORIA,FEMENINO,PREGRADO,PRESENCIAL,"INGENIERÍA DE PETRÓLEO, GAS NATURAL Y PETROQUÍ...",INGENIERÍA PETROQUÍMICA,6,20250630
17,83C97DE7F89B2705128B92C103D7840CCB56DFF2BADF98...,LIMA,LIMA METROPOLITANA,SAN MARTIN DE PORRES,2024,2,REGULARES,LIMA,LIMA METROPOLITANA,SAN MARTIN DE PORRES,...,LIMA,LIMA METROPOLITANA,LIMA,MASCULINO,PREGRADO,PRESENCIAL,"INGENIERÍA DE PETRÓLEO, GAS NATURAL Y PETROQUÍ...",INGENIERÍA DE PETRÓLEO Y GAS NATURAL,9,20250630
18,9B50F9B97758B1B2401C67EFA26E11A8BC0A35CBA7ED0A...,NO INDICA,NO INDICA,NO INDICA,2024,2,Cachimbos,LIMA,LIMA METROPOLITANA,SAN MARTIN DE PORRES,...,LIMA,LIMA METROPOLITANA,SAN MARTIN DE PORRES,FEMENINO,PREGRADO,PRESENCIAL,"INGENIERÍA DE PETRÓLEO, GAS NATURAL Y PETROQUÍ...",INGENIERÍA DE PETRÓLEO Y GAS NATURAL,1,20250630
19,D2B8D52295561A7BB426AF4571E98BA5D7AD4ACE089908...,LIMA,LIMA METROPOLITANA,SAN MARTIN DE PORRES,2024,2,REGULARES,LIMA,LIMA METROPOLITANA,SAN MARTIN DE PORRES,...,LIMA,LIMA METROPOLITANA,LIMA,FEMENINO,PREGRADO,PRESENCIAL,"INGENIERÍA DE PETRÓLEO, GAS NATURAL Y PETROQUÍ...",INGENIERÍA DE PETRÓLEO Y GAS NATURAL,7,20250630
20,BDEC008AD5CB402042A1A97ADF5647640094C3954BFC31...,LIMA,LIMA METROPOLITANA,VILLA EL SALVADOR,2024,2,REGULARES,LIMA,LIMA METROPOLITANA,VILLA EL SALVADOR,...,LIMA,LIMA METROPOLITANA,VILLA EL SALVADOR,MASCULINO,PREGRADO,PRESENCIAL,"INGENIERÍA DE PETRÓLEO, GAS NATURAL Y PETROQUÍ...",INGENIERÍA PETROQUÍMICA,6,20250630
21,037F6033ED06A5189D0004EA5900C5C8D5232545CD8AE2...,LIMA,LIMA METROPOLITANA,CHORRILLOS,2024,2,REGULARES,LIMA,LIMA METROPOLITANA,CHORRILLOS,...,LIMA,LIMA METROPOLITANA,CHORRILLOS,MASCULINO,PREGRADO,PRESENCIAL,"INGENIERÍA DE PETRÓLEO, GAS NATURAL Y PETROQUÍ...",INGENIERÍA PETROQUÍMICA,6,20250630
22,91AC5E153908583513EE74FC45A54C41738785531DD233...,HUANCAVELICA,ACOBAMBA,ACOBAMBA,2024,2,REGULARES,CALLAO,CALLAO,CALLAO,...,HUANCAVELICA,ACOBAMBA,ACOBAMBA,MASCULINO,PREGRADO,PRESENCIAL,"INGENIERÍA DE PETRÓLEO, GAS NATURAL Y PETROQUÍ...",INGENIERÍA DE PETRÓLEO Y GAS NATURAL,6,20250630
23,46DFB2AF01FDC7E247F821258D3CD8F8939552535BD4BC...,LIMA,LIMA METROPOLITANA,VILLA MARIA DEL TRIUNFO,2024,2,REGULARES,LIMA,LIMA METROPOLITANA,VILLA MARIA DEL TRIUNFO,...,LIMA,LIMA METROPOLITANA,VILLA EL SALVADOR,MASCULINO,PREGRADO,PRESENCIAL,"INGENIERÍA DE PETRÓLEO, GAS NATURAL Y PETROQUÍ...",INGENIERÍA DE PETRÓLEO Y GAS NATURAL,5,20250630
24,DD921D10B6941B504EA0A85AEBF0BD31A3F372159F2B23...,LIMA,LIMA METROPOLITANA,LOS OLIVOS,2024,2,REGULARES,LIMA,LIMA METROPOLITANA,LOS OLIVOS,...,LIMA,LIMA METROPOLITANA,LOS OLIVOS,FEMENINO,PREGRADO,PRESENCIAL,"INGENIERÍA DE PETRÓLEO, GAS NATURAL Y PETROQUÍ...",INGENIERÍA PETROQUÍMICA,5,20250630

In [ ]:
df_alumnos_uni_2.iloc[24500:]

,IDHASH,COLEGIO_DEPA,COLEGIO_PROV,COLEGIO_DIST,ANIO,PERIODO,TIPO_MATRICULA,DOMICILIO_DEPA,DOMICILIO_PROV,DOMICILIO_DIST,...,NACIMIENTO_DEPA,NACIMIENTO_PROV,NACIMIENTO_DIST,SEXO,MODALIDAD,METODOLOGIA,FACULTAD,ESPECIALIDAD,CICLO_RELATIVO,FECHA_CORTE
24500,05CF7356F173602A661C8488845F9BFE2E1CCED4B3E6B5...,TUMBES,TUMBES,TUMBES,2025,1,REGULARES,CALLAO,CALLAO,BELLAVISTA,...,TUMBES,TUMBES,CORRALES,FEMENINO,PREGRADO,PRESENCIAL,"INGENIERÍA DE PETRÓLEO, GAS NATURAL Y PETROQUÍ...",INGENIERÍA PETROQUÍMICA,3,20250630
24501,1F21FC599D3B111633EC946FF7DBA363BBD6478BAA76E0...,LIMA,LIMA METROPOLITANA,VILLA MARIA DEL TRIUNFO,2025,1,Cachimbos,LIMA,LIMA METROPOLITANA,VILLA MARIA DEL TRIUNFO,...,LIMA,LIMA METROPOLITANA,VILLA MARIA DEL TRIUNFO,MASCULINO,PREGRADO,PRESENCIAL,INGENIERÍA MECÁNICA,INGENIERÍA MECÁNICA Y ELÉCTRICA,1,20250630
24502,55CBE3E2AE7A4AD67F0D561D4B61296BD674BF5971FF6F...,ANCASH,POMABAMBA,PAROBAMBA,2025,1,REGULARES,LIMA,LIMA METROPOLITANA,SAN MARTIN DE PORRES,...,ANCASH,POMABAMBA,PAROBAMBA,MASCULINO,PREGRADO,PRESENCIAL,INGENIERÍA AMBIENTAL,INGENIERÍA SANITARIA,4,20250630
24503,0B96FD09DBD27DD7BE979531983801947102C80D1AA529...,JUNIN,HUANCAYO,EL TAMBO,2025,1,REGULARES,JUNIN,HUANCAYO,EL TAMBO,...,JUNIN,HUANCAYO,EL TAMBO,MASCULINO,PREGRADO,PRESENCIAL,INGENIERÍA ELÉCTRICA Y ELECTRÓNICA,INGENIERÍA DE TELECOMUNICACIONES,7,20250630
24504,FAF7C5931D6AD774E62E3407AF570E168EF396FE8F9189...,ANCASH,HUARMEY,HUARMEY,2025,1,Cachimbos,LIMA,LIMA METROPOLITANA,SAN MARTIN DE PORRES,...,LIMA,LIMA METROPOLITANA,SAN MARTIN DE PORRES,MASCULINO,PREGRADO,PRESENCIAL,"INGENIERÍA GEOLÓGICA, MINERA Y METALÚRGICA",INGENIERÍA DE MINAS,1,20250630
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24877,73074978180611CC8B9D40523BF4C286A7194742DE75E7...,LIMA,LIMA METROPOLITANA,CARABAYLLO,2025,1,REGULARES,LIMA,LIMA METROPOLITANA,COMAS,...,LIMA,LIMA METROPOLITANA,JESUS MARIA,MASCULINO,PREGRADO,PRESENCIAL,INGENIERÍA CIVIL,INGENIERÍA CIVIL,11,20250630
24878,F7819AD164959E40AE05A76C7150AE8D25B0575894E69A...,LIMA,LIMA METROPOLITANA,PUENTE PIEDRA,2025,1,REGULARES,LIMA,LIMA METROPOLITANA,PUENTE PIEDRA,...,LIMA,LIMA METROPOLITANA,PUENTE PIEDRA,FEMENINO,PREGRADO,PRESENCIAL,CIENCIAS,QUÍMICA,6,20250630
24879,D5A4E7716907039C1BC35B7ADFC7F15098854A25F2511A...,LIMA,LIMA METROPOLITANA,LOS OLIVOS,2025,1,REGULARES,LIMA,LIMA METROPOLITANA,SAN MIGUEL,...,LIMA,LIMA METROPOLITANA,MIRAFLORES,MASCULINO,PREGRADO,PRESENCIAL,INGENIERÍA INDUSTRIAL Y DE SISTEMAS,INGENIERÍA DE SISTEMAS,2,20250630
24880,4F19DD51DA3C2869BFC04D11352E96D6FD942B71DF9F57...,LIMA,CAÑETE,SAN VICENTE DE CAÑETE,2025,1,REGULARES,LIMA,CAÑETE,SAN VICENTE DE CAÑETE,...,LIMA,CAÑETE,SAN VICENTE DE CAÑETE,MASCULINO,PREGRADO,PRESENCIAL,INGENIERÍA AMBIENTAL,INGENIERÍA DE HIGIENE Y SEGURIDAD INDUSTRIAL,2,20250630
24881,BE93E75EA31505FD2E2585A38023D7973D80B8556FC097...,LIMA,LIMA METROPOLITANA,COMAS,2025,1,REGULARES,LIMA,LIMA METROPOLITANA,CARABAYLLO,...,LIMA,LIMA METROPOLITANA,CARABAYLLO,MASCULINO,PREGRADO,PRESENCIAL,INGENIERÍA MECÁNICA,INGENIERÍA MECATRÓNICA,1,20250630