In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

Dataset: Emisión de arbitrios municipales de la Municipalidad Distrital de Jesús María

https://www.datosabiertos.gob.pe/dataset/emisi%C3%B3n-de-arbitrios-municipales-de-la-municipalidad-distrital-de-jes%C3%BAs-mar%C3%ADa-mdjm

In [ ]:
dataset_arbitrios_jm = pd.read_csv('/content/drive/MyDrive/data_curso_python/dataset vf_3.csv', sep=';')

/tmp/ipython-input-1878783370.py:1: DtypeWarning: Columns (8,11,12,13) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset_arbitrios_jm = pd.read_csv('/content/drive/MyDrive/data_curso_python/dataset vf_3.csv', sep=';')

In [ ]:
dataset_arbitrios_jm.head()

,FECHA_CORTE,PERIODO,COD_CONTRIBUYENTE,NOM_CONTRIBUYENTE,COD_PREDIO,PORCENTAJE_CONDOMINIO,MONTO_PARQUE_JARDIN,MONTO_SERENAZGO,MONTO_RESIDUO_SOLIDO,MONTO_BARRIDO_CALLE,DESCUENTO_TOPE_PARQUE_JARDIN,DESCUENTO_TOPE_SERENAZGO,MONTO_TOPE_RESIDUO_SOLIDO,DESCUENTO_TOPE_BARRIO_CALLE,DEPARTAMENTO,PROVINCIA,DISTRITO,UBIGEO
0,20250424,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,565d7e9f0b7675ee7a7efa56447470fce66fe7529c77c9...,a12bd35bd44a509c187e686af353a2d1fe892f55eb1a84...,100.0,284.4,989.28,48.24,3.84,0.0,635.28,0,0,LIMA,LIMA,JESUS MARIA,150113
1,20250424,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,565d7e9f0b7675ee7a7efa56447470fce66fe7529c77c9...,ad1414d94fd434174e642227b1c9379e7d8b670e1e84dd...,100.0,284.4,989.28,"1,257.60",102.96,0.0,0,0,0,LIMA,LIMA,JESUS MARIA,150113
2,20250424,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,565d7e9f0b7675ee7a7efa56447470fce66fe7529c77c9...,60f944d54df6a65a219f1a188eeb150c92f16b3b9d7733...,100.0,284.4,"27,102.12","2,315.28",205.08,0.0,0,0,0,LIMA,LIMA,JESUS MARIA,150113
3,20250424,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,565d7e9f0b7675ee7a7efa56447470fce66fe7529c77c9...,7b3b030703a4554f65e694439c22c1f15b0a8fb070266a...,100.0,284.4,"3,651.36",299.64,18.36,0.0,0,0,0,LIMA,LIMA,JESUS MARIA,150113
4,20250424,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,565d7e9f0b7675ee7a7efa56447470fce66fe7529c77c9...,514e66f0e4a78921c67a3b54ce73d2073d659a9aadb48b...,100.0,284.4,989.28,839.64,68.76,0.0,0,0,0,LIMA,LIMA,JESUS MARIA,150113

In [ ]:
dataset_arbitrios_jm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 222874 entries, 0 to 222873
Data columns (total 18 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   FECHA_CORTE                   222874 non-null  int64
 1   PERIODO                       222874 non-null  int64
 2   COD_CONTRIBUYENTE             222874 non-null  object
 3   NOM_CONTRIBUYENTE             222874 non-null  object
 4   COD_PREDIO                    222874 non-null  object
 5   PORCENTAJE_CONDOMINIO         222874 non-null  float64
 6   MONTO_PARQUE_JARDIN           222874 non-null  float64
 7   MONTO_SERENAZGO               222874 non-null  object
 8   MONTO_RESIDUO_SOLIDO          222874 non-null  object
 9   MONTO_BARRIDO_CALLE           222874 non-null  object
 10  DESCUENTO_TOPE_PARQUE_JARDIN  222874 non-null  float64
 11  DESCUENTO_TOPE_SERENAZGO      222874 non-null  object
 12  MONTO_TOPE_RESIDUO_SOLIDO     222874 non-null  object
 13  DESCUENTO_TOPE_BARRIO_CALLE   222874 non-null  object
 14  DEPARTAMENTO                  222874 non-null  object
 15  PROVINCIA                     222874 non-null  object
 16  DISTRITO                      222874 non-null  object
 17  UBIGEO                        222874 non-null  int64
dtypes: float64(3), int64(3), object(12)
memory usage: 30.6+ MB

In [ ]:
dataset_arbitrios_jm['PERIODO'].unique()

array([2025, 2024, 2023])

In [ ]:
dataset_arbitrios_jm['UBIGEO'].unique()

array([150113])

#1. Cambio del tipo de dato de una columna

In [ ]:
import re

In [ ]:
def eliminar_coma(texto):

  texto_limpio = re.sub(r',', '', str(texto))

  return texto_limpio

In [ ]:
dataset_arbitrios_jm["MONTO_SERENAZGO"] = dataset_arbitrios_jm["MONTO_SERENAZGO"].apply(eliminar_coma)

In [ ]:
dataset_arbitrios_jm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 222874 entries, 0 to 222873
Data columns (total 18 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   FECHA_CORTE                   222874 non-null  int64
 1   PERIODO                       222874 non-null  int64
 2   COD_CONTRIBUYENTE             222874 non-null  object
 3   NOM_CONTRIBUYENTE             222874 non-null  object
 4   COD_PREDIO                    222874 non-null  object
 5   PORCENTAJE_CONDOMINIO         222874 non-null  float64
 6   MONTO_PARQUE_JARDIN           222874 non-null  float64
 7   MONTO_SERENAZGO               222874 non-null  object
 8   MONTO_RESIDUO_SOLIDO          222874 non-null  object
 9   MONTO_BARRIDO_CALLE           222874 non-null  object
 10  DESCUENTO_TOPE_PARQUE_JARDIN  222874 non-null  float64
 11  DESCUENTO_TOPE_SERENAZGO      222874 non-null  object
 12  MONTO_TOPE_RESIDUO_SOLIDO     222874 non-null  object
 13  DESCUENTO_TOPE_BARRIO_CALLE   222874 non-null  object
 14  DEPARTAMENTO                  222874 non-null  object
 15  PROVINCIA                     222874 non-null  object
 16  DISTRITO                      222874 non-null  object
 17  UBIGEO                        222874 non-null  int64
dtypes: float64(3), int64(3), object(12)
memory usage: 30.6+ MB

In [ ]:
dataset_arbitrios_jm["DESCUENTO_TOPE_SERENAZGO"] = dataset_arbitrios_jm["DESCUENTO_TOPE_SERENAZGO"].apply(eliminar_coma)

In [ ]:
dataset_arbitrios_jm.head()

,FECHA_CORTE,PERIODO,COD_CONTRIBUYENTE,NOM_CONTRIBUYENTE,COD_PREDIO,PORCENTAJE_CONDOMINIO,MONTO_PARQUE_JARDIN,MONTO_SERENAZGO,MONTO_RESIDUO_SOLIDO,MONTO_BARRIDO_CALLE,DESCUENTO_TOPE_PARQUE_JARDIN,DESCUENTO_TOPE_SERENAZGO,MONTO_TOPE_RESIDUO_SOLIDO,DESCUENTO_TOPE_BARRIO_CALLE,DEPARTAMENTO,PROVINCIA,DISTRITO,UBIGEO
0,20250424,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,565d7e9f0b7675ee7a7efa56447470fce66fe7529c77c9...,a12bd35bd44a509c187e686af353a2d1fe892f55eb1a84...,100.0,284.4,989.28,48.24,3.84,0.0,635.28,0,0,LIMA,LIMA,JESUS MARIA,150113
1,20250424,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,565d7e9f0b7675ee7a7efa56447470fce66fe7529c77c9...,ad1414d94fd434174e642227b1c9379e7d8b670e1e84dd...,100.0,284.4,989.28,"1,257.60",102.96,0.0,0,0,0,LIMA,LIMA,JESUS MARIA,150113
2,20250424,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,565d7e9f0b7675ee7a7efa56447470fce66fe7529c77c9...,60f944d54df6a65a219f1a188eeb150c92f16b3b9d7733...,100.0,284.4,27102.12,"2,315.28",205.08,0.0,0,0,0,LIMA,LIMA,JESUS MARIA,150113
3,20250424,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,565d7e9f0b7675ee7a7efa56447470fce66fe7529c77c9...,7b3b030703a4554f65e694439c22c1f15b0a8fb070266a...,100.0,284.4,3651.36,299.64,18.36,0.0,0,0,0,LIMA,LIMA,JESUS MARIA,150113
4,20250424,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,565d7e9f0b7675ee7a7efa56447470fce66fe7529c77c9...,514e66f0e4a78921c67a3b54ce73d2073d659a9aadb48b...,100.0,284.4,989.28,839.64,68.76,0.0,0,0,0,LIMA,LIMA,JESUS MARIA,150113

In [ ]:
dataset_arbitrios_jm["MONTO_SERENAZGO"] = dataset_arbitrios_jm["MONTO_SERENAZGO"].astype(float)

In [ ]:
dataset_arbitrios_jm["DESCUENTO_TOPE_SERENAZGO"] = dataset_arbitrios_jm["DESCUENTO_TOPE_SERENAZGO"].astype(float)

In [ ]:
dataset_arbitrios_jm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 222874 entries, 0 to 222873
Data columns (total 18 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   FECHA_CORTE                   222874 non-null  int64
 1   PERIODO                       222874 non-null  int64
 2   COD_CONTRIBUYENTE             222874 non-null  object
 3   NOM_CONTRIBUYENTE             222874 non-null  object
 4   COD_PREDIO                    222874 non-null  object
 5   PORCENTAJE_CONDOMINIO         222874 non-null  float64
 6   MONTO_PARQUE_JARDIN           222874 non-null  float64
 7   MONTO_SERENAZGO               222874 non-null  float64
 8   MONTO_RESIDUO_SOLIDO          222874 non-null  object
 9   MONTO_BARRIDO_CALLE           222874 non-null  object
 10  DESCUENTO_TOPE_PARQUE_JARDIN  222874 non-null  float64
 11  DESCUENTO_TOPE_SERENAZGO      222874 non-null  float64
 12  MONTO_TOPE_RESIDUO_SOLIDO     222874 non-null  object
 13  DESCUENTO_TOPE_BARRIO_CALLE   222874 non-null  object
 14  DEPARTAMENTO                  222874 non-null  object
 15  PROVINCIA                     222874 non-null  object
 16  DISTRITO                      222874 non-null  object
 17  UBIGEO                        222874 non-null  int64
dtypes: float64(5), int64(3), object(10)
memory usage: 30.6+ MB

#2. Concatenación de dataframes

## 2.1. Por filas

In [ ]:
data1 = dataset_arbitrios_jm.iloc[:5]

In [ ]:
data1

,FECHA_CORTE,PERIODO,COD_CONTRIBUYENTE,NOM_CONTRIBUYENTE,COD_PREDIO,PORCENTAJE_CONDOMINIO,MONTO_PARQUE_JARDIN,MONTO_SERENAZGO,MONTO_RESIDUO_SOLIDO,MONTO_BARRIDO_CALLE,DESCUENTO_TOPE_PARQUE_JARDIN,DESCUENTO_TOPE_SERENAZGO,MONTO_TOPE_RESIDUO_SOLIDO,DESCUENTO_TOPE_BARRIO_CALLE,DEPARTAMENTO,PROVINCIA,DISTRITO,UBIGEO
0,20250424,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,565d7e9f0b7675ee7a7efa56447470fce66fe7529c77c9...,a12bd35bd44a509c187e686af353a2d1fe892f55eb1a84...,100.0,284.4,989.28,48.24,3.84,0.0,635.28,0,0,LIMA,LIMA,JESUS MARIA,150113
1,20250424,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,565d7e9f0b7675ee7a7efa56447470fce66fe7529c77c9...,ad1414d94fd434174e642227b1c9379e7d8b670e1e84dd...,100.0,284.4,989.28,"1,257.60",102.96,0.0,0.00,0,0,LIMA,LIMA,JESUS MARIA,150113
2,20250424,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,565d7e9f0b7675ee7a7efa56447470fce66fe7529c77c9...,60f944d54df6a65a219f1a188eeb150c92f16b3b9d7733...,100.0,284.4,27102.12,"2,315.28",205.08,0.0,0.00,0,0,LIMA,LIMA,JESUS MARIA,150113
3,20250424,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,565d7e9f0b7675ee7a7efa56447470fce66fe7529c77c9...,7b3b030703a4554f65e694439c22c1f15b0a8fb070266a...,100.0,284.4,3651.36,299.64,18.36,0.0,0.00,0,0,LIMA,LIMA,JESUS MARIA,150113
4,20250424,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,565d7e9f0b7675ee7a7efa56447470fce66fe7529c77c9...,514e66f0e4a78921c67a3b54ce73d2073d659a9aadb48b...,100.0,284.4,989.28,839.64,68.76,0.0,0.00,0,0,LIMA,LIMA,JESUS MARIA,150113

In [ ]:
data2 = dataset_arbitrios_jm.iloc[200:205]

In [ ]:
data2

,FECHA_CORTE,PERIODO,COD_CONTRIBUYENTE,NOM_CONTRIBUYENTE,COD_PREDIO,PORCENTAJE_CONDOMINIO,MONTO_PARQUE_JARDIN,MONTO_SERENAZGO,MONTO_RESIDUO_SOLIDO,MONTO_BARRIDO_CALLE,DESCUENTO_TOPE_PARQUE_JARDIN,DESCUENTO_TOPE_SERENAZGO,MONTO_TOPE_RESIDUO_SOLIDO,DESCUENTO_TOPE_BARRIO_CALLE,DEPARTAMENTO,PROVINCIA,DISTRITO,UBIGEO
200,20250424,2025,139af841d2e577a63a242df67c26738d96e696da38a7cc...,5256c6034c019403f3539a760a568c4168ddc68354f050...,c02b2f32d2e14ca5d80a4124c4ba228a481bcacf8d737d...,100.0,0.0,0.0,0,0,0.0,0.0,0,0,LIMA,LIMA,JESUS MARIA,150113
201,20250424,2025,139af841d2e577a63a242df67c26738d96e696da38a7cc...,5256c6034c019403f3539a760a568c4168ddc68354f050...,3b170803faa4c7bcbd279afdcee901de64b021131486e4...,100.0,0.0,0.0,0,0,0.0,0.0,0,0,LIMA,LIMA,JESUS MARIA,150113
202,20250424,2025,139af841d2e577a63a242df67c26738d96e696da38a7cc...,5256c6034c019403f3539a760a568c4168ddc68354f050...,9f3e55c743a0782447409779013da843bc12c017ad7e0b...,100.0,0.0,0.0,0,0,0.0,0.0,0,0,LIMA,LIMA,JESUS MARIA,150113
203,20250424,2025,139af841d2e577a63a242df67c26738d96e696da38a7cc...,5256c6034c019403f3539a760a568c4168ddc68354f050...,7ff9713695f3290f2959167201db844eee5bf6019e18b8...,100.0,0.0,0.0,0,0,0.0,0.0,0,0,LIMA,LIMA,JESUS MARIA,150113
204,20250424,2025,139af841d2e577a63a242df67c26738d96e696da38a7cc...,5256c6034c019403f3539a760a568c4168ddc68354f050...,bcf85770a366ee2d74b959d9da33063066f183654b5faf...,100.0,0.0,0.0,0,0,0.0,0.0,0,0,LIMA,LIMA,JESUS MARIA,150113

In [ ]:
pd.concat([data1, data2])

,FECHA_CORTE,PERIODO,COD_CONTRIBUYENTE,NOM_CONTRIBUYENTE,COD_PREDIO,PORCENTAJE_CONDOMINIO,MONTO_PARQUE_JARDIN,MONTO_SERENAZGO,MONTO_RESIDUO_SOLIDO,MONTO_BARRIDO_CALLE,DESCUENTO_TOPE_PARQUE_JARDIN,DESCUENTO_TOPE_SERENAZGO,MONTO_TOPE_RESIDUO_SOLIDO,DESCUENTO_TOPE_BARRIO_CALLE,DEPARTAMENTO,PROVINCIA,DISTRITO,UBIGEO
0,20250424,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,565d7e9f0b7675ee7a7efa56447470fce66fe7529c77c9...,a12bd35bd44a509c187e686af353a2d1fe892f55eb1a84...,100.0,284.4,989.28,48.24,3.84,0.0,635.28,0,0,LIMA,LIMA,JESUS MARIA,150113
1,20250424,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,565d7e9f0b7675ee7a7efa56447470fce66fe7529c77c9...,ad1414d94fd434174e642227b1c9379e7d8b670e1e84dd...,100.0,284.4,989.28,"1,257.60",102.96,0.0,0.00,0,0,LIMA,LIMA,JESUS MARIA,150113
2,20250424,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,565d7e9f0b7675ee7a7efa56447470fce66fe7529c77c9...,60f944d54df6a65a219f1a188eeb150c92f16b3b9d7733...,100.0,284.4,27102.12,"2,315.28",205.08,0.0,0.00,0,0,LIMA,LIMA,JESUS MARIA,150113
3,20250424,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,565d7e9f0b7675ee7a7efa56447470fce66fe7529c77c9...,7b3b030703a4554f65e694439c22c1f15b0a8fb070266a...,100.0,284.4,3651.36,299.64,18.36,0.0,0.00,0,0,LIMA,LIMA,JESUS MARIA,150113
4,20250424,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,565d7e9f0b7675ee7a7efa56447470fce66fe7529c77c9...,514e66f0e4a78921c67a3b54ce73d2073d659a9aadb48b...,100.0,284.4,989.28,839.64,68.76,0.0,0.00,0,0,LIMA,LIMA,JESUS MARIA,150113
200,20250424,2025,139af841d2e577a63a242df67c26738d96e696da38a7cc...,5256c6034c019403f3539a760a568c4168ddc68354f050...,c02b2f32d2e14ca5d80a4124c4ba228a481bcacf8d737d...,100.0,0.0,0.00,0,0,0.0,0.00,0,0,LIMA,LIMA,JESUS MARIA,150113
201,20250424,2025,139af841d2e577a63a242df67c26738d96e696da38a7cc...,5256c6034c019403f3539a760a568c4168ddc68354f050...,3b170803faa4c7bcbd279afdcee901de64b021131486e4...,100.0,0.0,0.00,0,0,0.0,0.00,0,0,LIMA,LIMA,JESUS MARIA,150113
202,20250424,2025,139af841d2e577a63a242df67c26738d96e696da38a7cc...,5256c6034c019403f3539a760a568c4168ddc68354f050...,9f3e55c743a0782447409779013da843bc12c017ad7e0b...,100.0,0.0,0.00,0,0,0.0,0.00,0,0,LIMA,LIMA,JESUS MARIA,150113
203,20250424,2025,139af841d2e577a63a242df67c26738d96e696da38a7cc...,5256c6034c019403f3539a760a568c4168ddc68354f050...,7ff9713695f3290f2959167201db844eee5bf6019e18b8...,100.0,0.0,0.00,0,0,0.0,0.00,0,0,LIMA,LIMA,JESUS MARIA,150113
204,20250424,2025,139af841d2e577a63a242df67c26738d96e696da38a7cc...,5256c6034c019403f3539a760a568c4168ddc68354f050...,bcf85770a366ee2d74b959d9da33063066f183654b5faf...,100.0,0.0,0.00,0,0,0.0,0.00,0,0,LIMA,LIMA,JESUS MARIA,150113

In [ ]:
data3 = dataset_arbitrios_jm.iloc[10000:10003]

In [ ]:
data3

,FECHA_CORTE,PERIODO,COD_CONTRIBUYENTE,NOM_CONTRIBUYENTE,COD_PREDIO,PORCENTAJE_CONDOMINIO,MONTO_PARQUE_JARDIN,MONTO_SERENAZGO,MONTO_RESIDUO_SOLIDO,MONTO_BARRIDO_CALLE,DESCUENTO_TOPE_PARQUE_JARDIN,DESCUENTO_TOPE_SERENAZGO,MONTO_TOPE_RESIDUO_SOLIDO,DESCUENTO_TOPE_BARRIO_CALLE,DEPARTAMENTO,PROVINCIA,DISTRITO,UBIGEO
10000,20250424,2025,8183cc5137049691ccef4fe287609972136493636abab3...,6941f9aab037a0a1b83483cffb37756bb6fc212099246d...,9082fd227f0da4cf1114e025d4a6a418fb94c34917e270...,100.0,272.4,338.52,54.84,5.28,0.0,0.0,0,0,LIMA,LIMA,JESUS MARIA,150113
10001,20250424,2025,8183cc5137049691ccef4fe287609972136493636abab3...,6941f9aab037a0a1b83483cffb37756bb6fc212099246d...,559831926200f16d2561674aa7a1dbedefb47243346a1e...,100.0,272.4,338.52,83.88,6.96,0.0,0.0,0,0,LIMA,LIMA,JESUS MARIA,150113
10002,20250424,2025,8183cc5137049691ccef4fe287609972136493636abab3...,6941f9aab037a0a1b83483cffb37756bb6fc212099246d...,bfa238b93d257a259c61f9af281614d1d5d403944c7a42...,100.0,272.4,338.52,32.88,2.76,0.0,0.0,0,0,LIMA,LIMA,JESUS MARIA,150113

In [ ]:
pd.concat([data1, data2, data3])

,FECHA_CORTE,PERIODO,COD_CONTRIBUYENTE,NOM_CONTRIBUYENTE,COD_PREDIO,PORCENTAJE_CONDOMINIO,MONTO_PARQUE_JARDIN,MONTO_SERENAZGO,MONTO_RESIDUO_SOLIDO,MONTO_BARRIDO_CALLE,DESCUENTO_TOPE_PARQUE_JARDIN,DESCUENTO_TOPE_SERENAZGO,MONTO_TOPE_RESIDUO_SOLIDO,DESCUENTO_TOPE_BARRIO_CALLE,DEPARTAMENTO,PROVINCIA,DISTRITO,UBIGEO
0,20250424,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,565d7e9f0b7675ee7a7efa56447470fce66fe7529c77c9...,a12bd35bd44a509c187e686af353a2d1fe892f55eb1a84...,100.0,284.4,989.28,48.24,3.84,0.0,635.28,0,0,LIMA,LIMA,JESUS MARIA,150113
1,20250424,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,565d7e9f0b7675ee7a7efa56447470fce66fe7529c77c9...,ad1414d94fd434174e642227b1c9379e7d8b670e1e84dd...,100.0,284.4,989.28,"1,257.60",102.96,0.0,0.00,0,0,LIMA,LIMA,JESUS MARIA,150113
2,20250424,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,565d7e9f0b7675ee7a7efa56447470fce66fe7529c77c9...,60f944d54df6a65a219f1a188eeb150c92f16b3b9d7733...,100.0,284.4,27102.12,"2,315.28",205.08,0.0,0.00,0,0,LIMA,LIMA,JESUS MARIA,150113
3,20250424,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,565d7e9f0b7675ee7a7efa56447470fce66fe7529c77c9...,7b3b030703a4554f65e694439c22c1f15b0a8fb070266a...,100.0,284.4,3651.36,299.64,18.36,0.0,0.00,0,0,LIMA,LIMA,JESUS MARIA,150113
4,20250424,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,565d7e9f0b7675ee7a7efa56447470fce66fe7529c77c9...,514e66f0e4a78921c67a3b54ce73d2073d659a9aadb48b...,100.0,284.4,989.28,839.64,68.76,0.0,0.00,0,0,LIMA,LIMA,JESUS MARIA,150113
200,20250424,2025,139af841d2e577a63a242df67c26738d96e696da38a7cc...,5256c6034c019403f3539a760a568c4168ddc68354f050...,c02b2f32d2e14ca5d80a4124c4ba228a481bcacf8d737d...,100.0,0.0,0.00,0,0,0.0,0.00,0,0,LIMA,LIMA,JESUS MARIA,150113
201,20250424,2025,139af841d2e577a63a242df67c26738d96e696da38a7cc...,5256c6034c019403f3539a760a568c4168ddc68354f050...,3b170803faa4c7bcbd279afdcee901de64b021131486e4...,100.0,0.0,0.00,0,0,0.0,0.00,0,0,LIMA,LIMA,JESUS MARIA,150113
202,20250424,2025,139af841d2e577a63a242df67c26738d96e696da38a7cc...,5256c6034c019403f3539a760a568c4168ddc68354f050...,9f3e55c743a0782447409779013da843bc12c017ad7e0b...,100.0,0.0,0.00,0,0,0.0,0.00,0,0,LIMA,LIMA,JESUS MARIA,150113
203,20250424,2025,139af841d2e577a63a242df67c26738d96e696da38a7cc...,5256c6034c019403f3539a760a568c4168ddc68354f050...,7ff9713695f3290f2959167201db844eee5bf6019e18b8...,100.0,0.0,0.00,0,0,0.0,0.00,0,0,LIMA,LIMA,JESUS MARIA,150113
204,20250424,2025,139af841d2e577a63a242df67c26738d96e696da38a7cc...,5256c6034c019403f3539a760a568c4168ddc68354f050...,bcf85770a366ee2d74b959d9da33063066f183654b5faf...,100.0,0.0,0.00,0,0,0.0,0.00,0,0,LIMA,LIMA,JESUS MARIA,150113
10000,20250424,2025,8183cc5137049691ccef4fe287609972136493636abab3...,6941f9aab037a0a1b83483cffb37756bb6fc212099246d...,9082fd227f0da4cf1114e025d4a6a418fb94c34917e270...,100.0,272.4,338.52,54.84,5.28,0.0,0.00,0,0,LIMA,LIMA,JESUS MARIA,150113
10001,20250424,2025,8183cc5137049691ccef4fe287609972136493636abab3...,6941f9aab037a0a1b83483cffb37756bb6fc212099246d...,559831926200f16d2561674aa7a1dbedefb47243346a1e...,100.0,272.4,338.52,83.88,6.96,0.0,0.00,0,0,LIMA,LIMA,JESUS MARIA,150113
10002,20250424,2025,8183cc5137049691ccef4fe287609972136493636abab3...,6941f9aab037a0a1b83483cffb37756bb6fc212099246d...,bfa238b93d257a259c61f9af281614d1d5d403944c7a42...,100.0,272.4,338.52,32.88,2.76,0.0,0.00,0,0,LIMA,LIMA,JESUS MARIA,150113

##2.2. Por columnas

In [ ]:
df1 = dataset_arbitrios_jm.iloc[:1000].filter(['PERIODO', 'COD_CONTRIBUYENTE', 'COD_PREDIO', 'MONTO_PARQUE_JARDIN'])

In [ ]:
df1

,PERIODO,COD_CONTRIBUYENTE,COD_PREDIO,MONTO_PARQUE_JARDIN
0,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,a12bd35bd44a509c187e686af353a2d1fe892f55eb1a84...,284.4
1,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,ad1414d94fd434174e642227b1c9379e7d8b670e1e84dd...,284.4
2,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,60f944d54df6a65a219f1a188eeb150c92f16b3b9d7733...,284.4
3,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,7b3b030703a4554f65e694439c22c1f15b0a8fb070266a...,284.4
4,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,514e66f0e4a78921c67a3b54ce73d2073d659a9aadb48b...,284.4
...,...,...,...,...
995,2025,39ed9d9016f301c737a4a57f8da802a667b8384a139c7b...,c07eb226952c4acff5f19417f18063d691fe7221660f9a...,284.4
996,2025,39ed9d9016f301c737a4a57f8da802a667b8384a139c7b...,20d9a00885f27c28712d18965e4cf898f5cdd45a9aa008...,284.4
997,2025,39ed9d9016f301c737a4a57f8da802a667b8384a139c7b...,b8c49cc375c634986ff755d76bf82ad8ee4718233af2aa...,284.4
998,2025,39ed9d9016f301c737a4a57f8da802a667b8384a139c7b...,f85389345bd58f274d4d6b783498b4041e4b3cb3469515...,284.4
999,2025,39ed9d9016f301c737a4a57f8da802a667b8384a139c7b...,6b6579ae263c5e98e0836d84fce6b6937e178d0c08ce6b...,284.4

In [ ]:
df2 = dataset_arbitrios_jm.iloc[:1000].filter(['PERIODO', 'COD_CONTRIBUYENTE', 'COD_PREDIO', 'MONTO_SERENAZGO'])

In [ ]:
df2

,PERIODO,COD_CONTRIBUYENTE,COD_PREDIO,MONTO_SERENAZGO
0,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,a12bd35bd44a509c187e686af353a2d1fe892f55eb1a84...,989.28
1,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,ad1414d94fd434174e642227b1c9379e7d8b670e1e84dd...,989.28
2,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,60f944d54df6a65a219f1a188eeb150c92f16b3b9d7733...,27102.12
3,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,7b3b030703a4554f65e694439c22c1f15b0a8fb070266a...,3651.36
4,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,514e66f0e4a78921c67a3b54ce73d2073d659a9aadb48b...,989.28
...,...,...,...,...
995,2025,39ed9d9016f301c737a4a57f8da802a667b8384a139c7b...,c07eb226952c4acff5f19417f18063d691fe7221660f9a...,333.36
996,2025,39ed9d9016f301c737a4a57f8da802a667b8384a139c7b...,20d9a00885f27c28712d18965e4cf898f5cdd45a9aa008...,333.36
997,2025,39ed9d9016f301c737a4a57f8da802a667b8384a139c7b...,b8c49cc375c634986ff755d76bf82ad8ee4718233af2aa...,333.36
998,2025,39ed9d9016f301c737a4a57f8da802a667b8384a139c7b...,f85389345bd58f274d4d6b783498b4041e4b3cb3469515...,333.36
999,2025,39ed9d9016f301c737a4a57f8da802a667b8384a139c7b...,6b6579ae263c5e98e0836d84fce6b6937e178d0c08ce6b...,333.36

In [ ]:
df1.merge(df2, on=['PERIODO', 'COD_CONTRIBUYENTE', 'COD_PREDIO'], how='inner')

,PERIODO,COD_CONTRIBUYENTE,COD_PREDIO,MONTO_PARQUE_JARDIN,MONTO_SERENAZGO
0,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,a12bd35bd44a509c187e686af353a2d1fe892f55eb1a84...,284.4,989.28
1,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,ad1414d94fd434174e642227b1c9379e7d8b670e1e84dd...,284.4,989.28
2,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,60f944d54df6a65a219f1a188eeb150c92f16b3b9d7733...,284.4,27102.12
3,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,7b3b030703a4554f65e694439c22c1f15b0a8fb070266a...,284.4,3651.36
4,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,514e66f0e4a78921c67a3b54ce73d2073d659a9aadb48b...,284.4,989.28
...,...,...,...,...,...
995,2025,39ed9d9016f301c737a4a57f8da802a667b8384a139c7b...,c07eb226952c4acff5f19417f18063d691fe7221660f9a...,284.4,333.36
996,2025,39ed9d9016f301c737a4a57f8da802a667b8384a139c7b...,20d9a00885f27c28712d18965e4cf898f5cdd45a9aa008...,284.4,333.36
997,2025,39ed9d9016f301c737a4a57f8da802a667b8384a139c7b...,b8c49cc375c634986ff755d76bf82ad8ee4718233af2aa...,284.4,333.36
998,2025,39ed9d9016f301c737a4a57f8da802a667b8384a139c7b...,f85389345bd58f274d4d6b783498b4041e4b3cb3469515...,284.4,333.36
999,2025,39ed9d9016f301c737a4a57f8da802a667b8384a139c7b...,6b6579ae263c5e98e0836d84fce6b6937e178d0c08ce6b...,284.4,333.36

#3. Agregración, eliminación y edición de filas

In [ ]:
data_reducida_original = dataset_arbitrios_jm.iloc[:1000].filter(['COD_CONTRIBUYENTE', 'COD_PREDIO', 'MONTO_SERENAZGO'])

##3.1. Agregación

In [ ]:
data_reducida_tmp = data_reducida_original.copy()

In [ ]:
data_reducida_tmp

,COD_CONTRIBUYENTE,COD_PREDIO,MONTO_SERENAZGO
0,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,a12bd35bd44a509c187e686af353a2d1fe892f55eb1a84...,989.28
1,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,ad1414d94fd434174e642227b1c9379e7d8b670e1e84dd...,989.28
2,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,60f944d54df6a65a219f1a188eeb150c92f16b3b9d7733...,"27,102.12"
3,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,7b3b030703a4554f65e694439c22c1f15b0a8fb070266a...,"3,651.36"
4,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,514e66f0e4a78921c67a3b54ce73d2073d659a9aadb48b...,989.28
...,...,...,...
995,39ed9d9016f301c737a4a57f8da802a667b8384a139c7b...,c07eb226952c4acff5f19417f18063d691fe7221660f9a...,333.36
996,39ed9d9016f301c737a4a57f8da802a667b8384a139c7b...,20d9a00885f27c28712d18965e4cf898f5cdd45a9aa008...,333.36
997,39ed9d9016f301c737a4a57f8da802a667b8384a139c7b...,b8c49cc375c634986ff755d76bf82ad8ee4718233af2aa...,333.36
998,39ed9d9016f301c737a4a57f8da802a667b8384a139c7b...,f85389345bd58f274d4d6b783498b4041e4b3cb3469515...,333.36
999,39ed9d9016f301c737a4a57f8da802a667b8384a139c7b...,6b6579ae263c5e98e0836d84fce6b6937e178d0c08ce6b...,333.36

In [ ]:
data_reducida_tmp.loc[data_reducida_tmp.shape[0]] = ['abcdef', 'abcdef', 200]

In [ ]:
data_reducida_tmp

,COD_CONTRIBUYENTE,COD_PREDIO,MONTO_SERENAZGO
0,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,a12bd35bd44a509c187e686af353a2d1fe892f55eb1a84...,989.28
1,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,ad1414d94fd434174e642227b1c9379e7d8b670e1e84dd...,989.28
2,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,60f944d54df6a65a219f1a188eeb150c92f16b3b9d7733...,"27,102.12"
3,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,7b3b030703a4554f65e694439c22c1f15b0a8fb070266a...,"3,651.36"
4,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,514e66f0e4a78921c67a3b54ce73d2073d659a9aadb48b...,989.28
...,...,...,...
996,39ed9d9016f301c737a4a57f8da802a667b8384a139c7b...,20d9a00885f27c28712d18965e4cf898f5cdd45a9aa008...,333.36
997,39ed9d9016f301c737a4a57f8da802a667b8384a139c7b...,b8c49cc375c634986ff755d76bf82ad8ee4718233af2aa...,333.36
998,39ed9d9016f301c737a4a57f8da802a667b8384a139c7b...,f85389345bd58f274d4d6b783498b4041e4b3cb3469515...,333.36
999,39ed9d9016f301c737a4a57f8da802a667b8384a139c7b...,6b6579ae263c5e98e0836d84fce6b6937e178d0c08ce6b...,333.36
1000,abcdef,abcdef,200

In [ ]:
data_reducida_tmp.loc[1005] = ['uvwxyz', 'uvwxyz', 100]

In [ ]:
data_reducida_tmp

,COD_CONTRIBUYENTE,COD_PREDIO,MONTO_SERENAZGO
0,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,a12bd35bd44a509c187e686af353a2d1fe892f55eb1a84...,989.28
1,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,ad1414d94fd434174e642227b1c9379e7d8b670e1e84dd...,989.28
2,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,60f944d54df6a65a219f1a188eeb150c92f16b3b9d7733...,"27,102.12"
3,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,7b3b030703a4554f65e694439c22c1f15b0a8fb070266a...,"3,651.36"
4,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,514e66f0e4a78921c67a3b54ce73d2073d659a9aadb48b...,989.28
...,...,...,...
997,39ed9d9016f301c737a4a57f8da802a667b8384a139c7b...,b8c49cc375c634986ff755d76bf82ad8ee4718233af2aa...,333.36
998,39ed9d9016f301c737a4a57f8da802a667b8384a139c7b...,f85389345bd58f274d4d6b783498b4041e4b3cb3469515...,333.36
999,39ed9d9016f301c737a4a57f8da802a667b8384a139c7b...,6b6579ae263c5e98e0836d84fce6b6937e178d0c08ce6b...,333.36
1000,abcdef,abcdef,200
1005,uvwxyz,uvwxyz,100

##3.2. Eliminación

In [ ]:
data_reducida_tmp = data_reducida_original.copy()

In [ ]:
data_reducida_tmp.drop(index=[0,1,5])

,COD_CONTRIBUYENTE,COD_PREDIO,MONTO_SERENAZGO
2,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,60f944d54df6a65a219f1a188eeb150c92f16b3b9d7733...,"27,102.12"
3,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,7b3b030703a4554f65e694439c22c1f15b0a8fb070266a...,"3,651.36"
4,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,514e66f0e4a78921c67a3b54ce73d2073d659a9aadb48b...,989.28
6,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,b43aa509b1ad0942d2ee14a5f5d604b33d3cfb65f5c3ac...,"27,102.12"
7,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,5f6cc3d54a99d8703aedee3e693d06d10c0c41a0344e9b...,338.52
...,...,...,...
995,39ed9d9016f301c737a4a57f8da802a667b8384a139c7b...,c07eb226952c4acff5f19417f18063d691fe7221660f9a...,333.36
996,39ed9d9016f301c737a4a57f8da802a667b8384a139c7b...,20d9a00885f27c28712d18965e4cf898f5cdd45a9aa008...,333.36
997,39ed9d9016f301c737a4a57f8da802a667b8384a139c7b...,b8c49cc375c634986ff755d76bf82ad8ee4718233af2aa...,333.36
998,39ed9d9016f301c737a4a57f8da802a667b8384a139c7b...,f85389345bd58f274d4d6b783498b4041e4b3cb3469515...,333.36
999,39ed9d9016f301c737a4a57f8da802a667b8384a139c7b...,6b6579ae263c5e98e0836d84fce6b6937e178d0c08ce6b...,333.36

##3.3. Edición

In [ ]:
data_reducida_tmp = data_reducida_original.copy()

In [ ]:
data_reducida_tmp.loc[2] = ['abcdef', 'abcdef', 200]

In [ ]:
data_reducida_tmp

,COD_CONTRIBUYENTE,COD_PREDIO,MONTO_SERENAZGO
0,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,a12bd35bd44a509c187e686af353a2d1fe892f55eb1a84...,989.28
1,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,ad1414d94fd434174e642227b1c9379e7d8b670e1e84dd...,989.28
2,abcdef,abcdef,200
3,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,7b3b030703a4554f65e694439c22c1f15b0a8fb070266a...,"3,651.36"
4,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,514e66f0e4a78921c67a3b54ce73d2073d659a9aadb48b...,989.28
...,...,...,...
995,39ed9d9016f301c737a4a57f8da802a667b8384a139c7b...,c07eb226952c4acff5f19417f18063d691fe7221660f9a...,333.36
996,39ed9d9016f301c737a4a57f8da802a667b8384a139c7b...,20d9a00885f27c28712d18965e4cf898f5cdd45a9aa008...,333.36
997,39ed9d9016f301c737a4a57f8da802a667b8384a139c7b...,b8c49cc375c634986ff755d76bf82ad8ee4718233af2aa...,333.36
998,39ed9d9016f301c737a4a57f8da802a667b8384a139c7b...,f85389345bd58f274d4d6b783498b4041e4b3cb3469515...,333.36
999,39ed9d9016f301c737a4a57f8da802a667b8384a139c7b...,6b6579ae263c5e98e0836d84fce6b6937e178d0c08ce6b...,333.36

#4. Agregación, eliminación y edición de columnas

##4.1. Agregación

In [ ]:
data_reducida_original = dataset_arbitrios_jm.filter(['PERIODO', 'COD_CONTRIBUYENTE', 'COD_PREDIO', 'MONTO_SERENAZGO', 'DEPARTAMENTO',
                                                      'PROVINCIA', 'DISTRITO', 'UBIGEO'])

In [ ]:
data_reducida_tmp = data_reducida_original.copy()

In [ ]:
data_reducida_tmp["FLAG_PAGADOR"] = "X"

In [ ]:
data_reducida_tmp

,PERIODO,COD_CONTRIBUYENTE,COD_PREDIO,MONTO_SERENAZGO,DEPARTAMENTO,PROVINCIA,DISTRITO,UBIGEO,FLAG_PAGADOR
0,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,a12bd35bd44a509c187e686af353a2d1fe892f55eb1a84...,989.28,LIMA,LIMA,JESUS MARIA,150113,X
1,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,ad1414d94fd434174e642227b1c9379e7d8b670e1e84dd...,989.28,LIMA,LIMA,JESUS MARIA,150113,X
2,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,60f944d54df6a65a219f1a188eeb150c92f16b3b9d7733...,"27,102.12",LIMA,LIMA,JESUS MARIA,150113,X
3,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,7b3b030703a4554f65e694439c22c1f15b0a8fb070266a...,"3,651.36",LIMA,LIMA,JESUS MARIA,150113,X
4,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,514e66f0e4a78921c67a3b54ce73d2073d659a9aadb48b...,989.28,LIMA,LIMA,JESUS MARIA,150113,X
...,...,...,...,...,...,...,...,...,...
222869,2023,066f56a4ba1b0f94bbb4deb092efc27384759337dccce1...,9a283b1c77e825ae9e749395e2211e9a7dc13721576fe5...,321,LIMA,LIMA,JESUS MARIA,150113,X
222870,2023,c3edb578cfde39bc9028bb6d95f2ac75390de3a1108d59...,69fb815dc8767ab941dbbb2d47a06ee67e6f4462318d67...,321,LIMA,LIMA,JESUS MARIA,150113,X
222871,2023,15c7a113b18551acbd5f0e9a5994611cabc62623195b7e...,d82371c93a310a6373f10e356508d7f8289a1aca0f4484...,321,LIMA,LIMA,JESUS MARIA,150113,X
222872,2023,216e94dcef3f99725bfbb7b501f570295d35ac45ffbe46...,dadbb4366e9732f9479a070839c7ac8a1aab7e54843fab...,0,LIMA,LIMA,JESUS MARIA,150113,X
222873,2023,1617b55744917032e13bd0776876f0bba617565262e397...,65ffb0938dd2589293360b12dda5197b875c6883790bff...,886.2,LIMA,LIMA,JESUS MARIA,150113,X

##4.2. Eliminación

In [ ]:
data_reducida_tmp = data_reducida_original.copy()

In [ ]:
data_reducida_tmp.drop(columns=['DEPARTAMENTO', 'PROVINCIA', 'DISTRITO'])

,PERIODO,COD_CONTRIBUYENTE,COD_PREDIO,MONTO_SERENAZGO,UBIGEO
0,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,a12bd35bd44a509c187e686af353a2d1fe892f55eb1a84...,989.28,150113
1,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,ad1414d94fd434174e642227b1c9379e7d8b670e1e84dd...,989.28,150113
2,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,60f944d54df6a65a219f1a188eeb150c92f16b3b9d7733...,"27,102.12",150113
3,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,7b3b030703a4554f65e694439c22c1f15b0a8fb070266a...,"3,651.36",150113
4,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,514e66f0e4a78921c67a3b54ce73d2073d659a9aadb48b...,989.28,150113
...,...,...,...,...,...
222869,2023,066f56a4ba1b0f94bbb4deb092efc27384759337dccce1...,9a283b1c77e825ae9e749395e2211e9a7dc13721576fe5...,321,150113
222870,2023,c3edb578cfde39bc9028bb6d95f2ac75390de3a1108d59...,69fb815dc8767ab941dbbb2d47a06ee67e6f4462318d67...,321,150113
222871,2023,15c7a113b18551acbd5f0e9a5994611cabc62623195b7e...,d82371c93a310a6373f10e356508d7f8289a1aca0f4484...,321,150113
222872,2023,216e94dcef3f99725bfbb7b501f570295d35ac45ffbe46...,dadbb4366e9732f9479a070839c7ac8a1aab7e54843fab...,0,150113
222873,2023,1617b55744917032e13bd0776876f0bba617565262e397...,65ffb0938dd2589293360b12dda5197b875c6883790bff...,886.2,150113

In [ ]:
data_reducida_tmp_2 = data_reducida_tmp.drop(columns=['DEPARTAMENTO', 'PROVINCIA', 'DISTRITO'])

In [ ]:
data_reducida_tmp_2

,PERIODO,COD_CONTRIBUYENTE,COD_PREDIO,MONTO_SERENAZGO,UBIGEO
0,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,a12bd35bd44a509c187e686af353a2d1fe892f55eb1a84...,989.28,150113
1,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,ad1414d94fd434174e642227b1c9379e7d8b670e1e84dd...,989.28,150113
2,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,60f944d54df6a65a219f1a188eeb150c92f16b3b9d7733...,"27,102.12",150113
3,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,7b3b030703a4554f65e694439c22c1f15b0a8fb070266a...,"3,651.36",150113
4,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,514e66f0e4a78921c67a3b54ce73d2073d659a9aadb48b...,989.28,150113
...,...,...,...,...,...
222869,2023,066f56a4ba1b0f94bbb4deb092efc27384759337dccce1...,9a283b1c77e825ae9e749395e2211e9a7dc13721576fe5...,321,150113
222870,2023,c3edb578cfde39bc9028bb6d95f2ac75390de3a1108d59...,69fb815dc8767ab941dbbb2d47a06ee67e6f4462318d67...,321,150113
222871,2023,15c7a113b18551acbd5f0e9a5994611cabc62623195b7e...,d82371c93a310a6373f10e356508d7f8289a1aca0f4484...,321,150113
222872,2023,216e94dcef3f99725bfbb7b501f570295d35ac45ffbe46...,dadbb4366e9732f9479a070839c7ac8a1aab7e54843fab...,0,150113
222873,2023,1617b55744917032e13bd0776876f0bba617565262e397...,65ffb0938dd2589293360b12dda5197b875c6883790bff...,886.2,150113

In [ ]:
data_reducida_tmp.drop(columns=['DEPARTAMENTO', 'PROVINCIA', 'DISTRITO'], inplace=True)

In [ ]:
data_reducida_tmp

,PERIODO,COD_CONTRIBUYENTE,COD_PREDIO,MONTO_SERENAZGO,UBIGEO
0,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,a12bd35bd44a509c187e686af353a2d1fe892f55eb1a84...,989.28,150113
1,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,ad1414d94fd434174e642227b1c9379e7d8b670e1e84dd...,989.28,150113
2,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,60f944d54df6a65a219f1a188eeb150c92f16b3b9d7733...,"27,102.12",150113
3,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,7b3b030703a4554f65e694439c22c1f15b0a8fb070266a...,"3,651.36",150113
4,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,514e66f0e4a78921c67a3b54ce73d2073d659a9aadb48b...,989.28,150113
...,...,...,...,...,...
222869,2023,066f56a4ba1b0f94bbb4deb092efc27384759337dccce1...,9a283b1c77e825ae9e749395e2211e9a7dc13721576fe5...,321,150113
222870,2023,c3edb578cfde39bc9028bb6d95f2ac75390de3a1108d59...,69fb815dc8767ab941dbbb2d47a06ee67e6f4462318d67...,321,150113
222871,2023,15c7a113b18551acbd5f0e9a5994611cabc62623195b7e...,d82371c93a310a6373f10e356508d7f8289a1aca0f4484...,321,150113
222872,2023,216e94dcef3f99725bfbb7b501f570295d35ac45ffbe46...,dadbb4366e9732f9479a070839c7ac8a1aab7e54843fab...,0,150113
222873,2023,1617b55744917032e13bd0776876f0bba617565262e397...,65ffb0938dd2589293360b12dda5197b875c6883790bff...,886.2,150113

##4.3. Edición

In [ ]:
data_reducida_tmp = data_reducida_original.copy()

In [ ]:
data_reducida_tmp["MONTO_SERENAZGO"] = data_reducida_tmp['MONTO_SERENAZGO'].apply(lambda x: 0 if x < 1000 else x)

In [ ]:
data_reducida_tmp

,PERIODO,COD_CONTRIBUYENTE,COD_PREDIO,MONTO_SERENAZGO,DEPARTAMENTO,PROVINCIA,DISTRITO,UBIGEO
0,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,a12bd35bd44a509c187e686af353a2d1fe892f55eb1a84...,0.00,LIMA,LIMA,JESUS MARIA,150113
1,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,ad1414d94fd434174e642227b1c9379e7d8b670e1e84dd...,0.00,LIMA,LIMA,JESUS MARIA,150113
2,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,60f944d54df6a65a219f1a188eeb150c92f16b3b9d7733...,27102.12,LIMA,LIMA,JESUS MARIA,150113
3,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,7b3b030703a4554f65e694439c22c1f15b0a8fb070266a...,3651.36,LIMA,LIMA,JESUS MARIA,150113
4,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,514e66f0e4a78921c67a3b54ce73d2073d659a9aadb48b...,0.00,LIMA,LIMA,JESUS MARIA,150113
...,...,...,...,...,...,...,...,...
222869,2023,066f56a4ba1b0f94bbb4deb092efc27384759337dccce1...,9a283b1c77e825ae9e749395e2211e9a7dc13721576fe5...,0.00,LIMA,LIMA,JESUS MARIA,150113
222870,2023,c3edb578cfde39bc9028bb6d95f2ac75390de3a1108d59...,69fb815dc8767ab941dbbb2d47a06ee67e6f4462318d67...,0.00,LIMA,LIMA,JESUS MARIA,150113
222871,2023,15c7a113b18551acbd5f0e9a5994611cabc62623195b7e...,d82371c93a310a6373f10e356508d7f8289a1aca0f4484...,0.00,LIMA,LIMA,JESUS MARIA,150113
222872,2023,216e94dcef3f99725bfbb7b501f570295d35ac45ffbe46...,dadbb4366e9732f9479a070839c7ac8a1aab7e54843fab...,0.00,LIMA,LIMA,JESUS MARIA,150113
222873,2023,1617b55744917032e13bd0776876f0bba617565262e397...,65ffb0938dd2589293360b12dda5197b875c6883790bff...,0.00,LIMA,LIMA,JESUS MARIA,150113

#5. Funciones matemáticas en Pandas

In [ ]:
data_reducida_original['MONTO_SERENAZGO']

0           989.28
1           989.28
2         27102.12
3          3651.36
4           989.28
            ...
222869      321.00
222870      321.00
222871      321.00
222872        0.00
222873      886.20
Name: MONTO_SERENAZGO, Length: 222874, dtype: float64

In [ ]:
data_reducida_original.MONTO_SERENAZGO

0           989.28
1           989.28
2         27102.12
3          3651.36
4           989.28
            ...
222869      321.00
222870      321.00
222871      321.00
222872        0.00
222873      886.20
Name: MONTO_SERENAZGO, Length: 222874, dtype: float64

In [ ]:
data_reducida_original.MONTO_SERENAZGO.add(10)

0           999.28
1           999.28
2         27112.12
3          3661.36
4           999.28
            ...
222869      331.00
222870      331.00
222871      331.00
222872       10.00
222873      896.20
Name: MONTO_SERENAZGO, Length: 222874, dtype: float64

In [ ]:
data_reducida_original.MONTO_SERENAZGO.sub(50)

0           939.28
1           939.28
2         27052.12
3          3601.36
4           939.28
            ...
222869      271.00
222870      271.00
222871      271.00
222872      -50.00
222873      836.20
Name: MONTO_SERENAZGO, Length: 222874, dtype: float64

In [ ]:
data_reducida_original.MONTO_SERENAZGO.div(100)

0           9.8928
1           9.8928
2         271.0212
3          36.5136
4           9.8928
            ...
222869      3.2100
222870      3.2100
222871      3.2100
222872      0.0000
222873      8.8620
Name: MONTO_SERENAZGO, Length: 222874, dtype: float64

In [ ]:
data_reducida_original.MONTO_SERENAZGO.mul(2)

0          1978.56
1          1978.56
2         54204.24
3          7302.72
4          1978.56
            ...
222869      642.00
222870      642.00
222871      642.00
222872        0.00
222873     1772.40
Name: MONTO_SERENAZGO, Length: 222874, dtype: float64

In [ ]:
data_reducida_original.MONTO_SERENAZGO.mod(2)

0         1.28
1         1.28
2         0.12
3         1.36
4         1.28
          ...
222869    1.00
222870    1.00
222871    1.00
222872    0.00
222873    0.20
Name: MONTO_SERENAZGO, Length: 222874, dtype: float64

In [ ]:
data_reducida_original.MONTO_SERENAZGO.pow(0.5)

0          31.452822
1          31.452822
2         164.627215
3          60.426484
4          31.452822
             ...
222869     17.916473
222870     17.916473
222871     17.916473
222872      0.000000
222873     29.769112
Name: MONTO_SERENAZGO, Length: 222874, dtype: float64

In [ ]:
data_reducida_original_2 = dataset_arbitrios_jm.iloc[:1000].filter(['COD_CONTRIBUYENTE', 'COD_PREDIO', 'MONTO_SERENAZGO', 'MONTO_PARQUE_JARDIN'])

In [ ]:
data_reducida_original_2.filter(['MONTO_PARQUE_JARDIN', 'MONTO_SERENAZGO'])

     MONTO_PARQUE_JARDIN  MONTO_SERENAZGO
0                  284.4           989.28
1                  284.4           989.28
2                  284.4         27102.12
3                  284.4          3651.36
4                  284.4           989.28
..                   ...              ...
995                284.4           333.36
996                284.4           333.36
997                284.4           333.36
998                284.4           333.36
999                284.4           333.36

[1000 rows x 2 columns]

In [ ]:
data_reducida_original_2.filter(['MONTO_PARQUE_JARDIN', 'MONTO_SERENAZGO']).pow(2)

     MONTO_PARQUE_JARDIN  MONTO_SERENAZGO
0               80883.36     9.786749e+05
1               80883.36     9.786749e+05
2               80883.36     7.345249e+08
3               80883.36     1.333243e+07
4               80883.36     9.786749e+05
..                   ...              ...
995             80883.36     1.111289e+05
996             80883.36     1.111289e+05
997             80883.36     1.111289e+05
998             80883.36     1.111289e+05
999             80883.36     1.111289e+05

[1000 rows x 2 columns]

#6. Operadores en Pandas

##6.1. Aritméticos

In [ ]:
dataset_arbitrios_jm.MONTO_SERENAZGO + dataset_arbitrios_jm.MONTO_PARQUE_JARDIN

0          1273.68
1          1273.68
2         27386.52
3          3935.76
4          1273.68
            ...
222869      617.16
222870      619.80
222871      617.16
222872        0.00
222873     1182.36
Length: 222874, dtype: float64

In [ ]:
dataset_arbitrios_jm.MONTO_SERENAZGO - dataset_arbitrios_jm.DESCUENTO_TOPE_SERENAZGO

0           354.00
1           989.28
2         27102.12
3          3651.36
4           989.28
            ...
222869      321.00
222870      268.68
222871      268.68
222872        0.00
222873      741.24
Length: 222874, dtype: float64

In [ ]:
dataset_arbitrios_jm.MONTO_SERENAZGO * 2

0          1978.56
1          1978.56
2         54204.24
3          7302.72
4          1978.56
            ...
222869      642.00
222870      642.00
222871      642.00
222872        0.00
222873     1772.40
Name: MONTO_SERENAZGO, Length: 222874, dtype: float64

In [ ]:
dataset_arbitrios_jm.MONTO_SERENAZGO / 100

0           9.8928
1           9.8928
2         271.0212
3          36.5136
4           9.8928
            ...
222869      3.2100
222870      3.2100
222871      3.2100
222872      0.0000
222873      8.8620
Name: MONTO_SERENAZGO, Length: 222874, dtype: float64

##6.2. De comparación

In [ ]:
dataset_arbitrios_jm.MONTO_SERENAZGO == 989.28

0          True
1          True
2         False
3         False
4          True
          ...
222869    False
222870    False
222871    False
222872    False
222873    False
Name: MONTO_SERENAZGO, Length: 222874, dtype: bool

In [ ]:
dataset_arbitrios_jm.MONTO_SERENAZGO != 989.28

0         False
1         False
2          True
3          True
4         False
          ...
222869     True
222870     True
222871     True
222872     True
222873     True
Name: MONTO_SERENAZGO, Length: 222874, dtype: bool

In [ ]:
dataset_arbitrios_jm.MONTO_SERENAZGO > 500

0          True
1          True
2          True
3          True
4          True
          ...
222869    False
222870    False
222871    False
222872    False
222873     True
Name: MONTO_SERENAZGO, Length: 222874, dtype: bool

In [ ]:
dataset_arbitrios_jm.MONTO_SERENAZGO < 1000

0          True
1          True
2         False
3         False
4          True
          ...
222869     True
222870     True
222871     True
222872     True
222873     True
Name: MONTO_SERENAZGO, Length: 222874, dtype: bool

##6.3. Lógicos

In [ ]:
(dataset_arbitrios_jm.MONTO_SERENAZGO > 500) & (dataset_arbitrios_jm.MONTO_SERENAZGO < 1000)

0          True
1          True
2         False
3         False
4          True
          ...
222869    False
222870    False
222871    False
222872    False
222873     True
Name: MONTO_SERENAZGO, Length: 222874, dtype: bool

In [ ]:
dataset_arbitrios_jm.loc[(dataset_arbitrios_jm.PERIODO == 2024) | (dataset_arbitrios_jm.PERIODO == 2025)]

,FECHA_CORTE,PERIODO,COD_CONTRIBUYENTE,NOM_CONTRIBUYENTE,COD_PREDIO,PORCENTAJE_CONDOMINIO,MONTO_PARQUE_JARDIN,MONTO_SERENAZGO,MONTO_RESIDUO_SOLIDO,MONTO_BARRIDO_CALLE,DESCUENTO_TOPE_PARQUE_JARDIN,DESCUENTO_TOPE_SERENAZGO,MONTO_TOPE_RESIDUO_SOLIDO,DESCUENTO_TOPE_BARRIO_CALLE,DEPARTAMENTO,PROVINCIA,DISTRITO,UBIGEO
0,20250424,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,565d7e9f0b7675ee7a7efa56447470fce66fe7529c77c9...,a12bd35bd44a509c187e686af353a2d1fe892f55eb1a84...,100.0,284.40,989.28,48.24,3.84,0.0,635.28,0,0,LIMA,LIMA,JESUS MARIA,150113
1,20250424,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,565d7e9f0b7675ee7a7efa56447470fce66fe7529c77c9...,ad1414d94fd434174e642227b1c9379e7d8b670e1e84dd...,100.0,284.40,989.28,"1,257.60",102.96,0.0,0.00,0,0,LIMA,LIMA,JESUS MARIA,150113
2,20250424,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,565d7e9f0b7675ee7a7efa56447470fce66fe7529c77c9...,60f944d54df6a65a219f1a188eeb150c92f16b3b9d7733...,100.0,284.40,27102.12,"2,315.28",205.08,0.0,0.00,0,0,LIMA,LIMA,JESUS MARIA,150113
3,20250424,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,565d7e9f0b7675ee7a7efa56447470fce66fe7529c77c9...,7b3b030703a4554f65e694439c22c1f15b0a8fb070266a...,100.0,284.40,3651.36,299.64,18.36,0.0,0.00,0,0,LIMA,LIMA,JESUS MARIA,150113
4,20250424,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,565d7e9f0b7675ee7a7efa56447470fce66fe7529c77c9...,514e66f0e4a78921c67a3b54ce73d2073d659a9aadb48b...,100.0,284.40,989.28,839.64,68.76,0.0,0.00,0,0,LIMA,LIMA,JESUS MARIA,150113
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152988,20250424,2024,334eb0b9a575b80869c09347d1b4adcf178d7a1ca99edc...,43058f1c9bf0c88c7df756f7f483be1ff45f5150944163...,9fe628b61b3359f152973069c05e8efacda800aa693953...,100.0,308.64,326.52,111.6,9.72,0.0,8.28,15.24,0.0,LIMA,LIMA,JESUS MARIA,150113
152989,20250424,2024,541192e0644cfe53b37031223334b09c014ae4d85cd34c...,0d90cddaea9c5e696cc1041112fdb8355344dd12ad829b...,059d8a0149b8b87494138200745346f8a449a9d4799deb...,100.0,0.00,0.00,0,0,0.0,0.00,0,0.0,LIMA,LIMA,JESUS MARIA,150113
152990,20250424,2024,541192e0644cfe53b37031223334b09c014ae4d85cd34c...,0d90cddaea9c5e696cc1041112fdb8355344dd12ad829b...,29989210926a8609226abbc5d6d4a0332e8594c0d7e950...,100.0,282.00,326.52,63.84,1.2,0.0,0.00,15.84,0.0,LIMA,LIMA,JESUS MARIA,150113
152991,20250424,2024,893f5ad546ed66d5e2f8cee938272afe51c2dbd4e5c521...,270fee5085a7e941321b676b2e91f4ed6cdc722f0178da...,4410608064f565619584265b377168b4180a0cf48b81a2...,50.0,154.32,163.26,24.06,8.28,0.0,0.00,0,0.0,LIMA,LIMA,JESUS MARIA,150113
152992,20250424,2024,70803d2b23c1eb1cd3d56291ada2696b23b9baf2e677ab...,ee6e7834eb525e51e0c90997408dc8a7067184ad7a8091...,4410608064f565619584265b377168b4180a0cf48b81a2...,50.0,154.32,163.26,24.06,8.28,0.0,0.00,0,0.0,LIMA,LIMA,JESUS MARIA,150113

In [ ]:
dataset_arbitrios_jm.loc[~(dataset_arbitrios_jm.MONTO_SERENAZGO == 0)]

,FECHA_CORTE,PERIODO,COD_CONTRIBUYENTE,NOM_CONTRIBUYENTE,COD_PREDIO,PORCENTAJE_CONDOMINIO,MONTO_PARQUE_JARDIN,MONTO_SERENAZGO,MONTO_RESIDUO_SOLIDO,MONTO_BARRIDO_CALLE,DESCUENTO_TOPE_PARQUE_JARDIN,DESCUENTO_TOPE_SERENAZGO,MONTO_TOPE_RESIDUO_SOLIDO,DESCUENTO_TOPE_BARRIO_CALLE,DEPARTAMENTO,PROVINCIA,DISTRITO,UBIGEO
0,20250424,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,565d7e9f0b7675ee7a7efa56447470fce66fe7529c77c9...,a12bd35bd44a509c187e686af353a2d1fe892f55eb1a84...,100.0,284.40,989.28,48.24,3.84,0.0,635.28,0,0,LIMA,LIMA,JESUS MARIA,150113
1,20250424,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,565d7e9f0b7675ee7a7efa56447470fce66fe7529c77c9...,ad1414d94fd434174e642227b1c9379e7d8b670e1e84dd...,100.0,284.40,989.28,"1,257.60",102.96,0.0,0.00,0,0,LIMA,LIMA,JESUS MARIA,150113
2,20250424,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,565d7e9f0b7675ee7a7efa56447470fce66fe7529c77c9...,60f944d54df6a65a219f1a188eeb150c92f16b3b9d7733...,100.0,284.40,27102.12,"2,315.28",205.08,0.0,0.00,0,0,LIMA,LIMA,JESUS MARIA,150113
3,20250424,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,565d7e9f0b7675ee7a7efa56447470fce66fe7529c77c9...,7b3b030703a4554f65e694439c22c1f15b0a8fb070266a...,100.0,284.40,3651.36,299.64,18.36,0.0,0.00,0,0,LIMA,LIMA,JESUS MARIA,150113
4,20250424,2025,24800e41b771be6a3156c9f5fac4e78bb27675160b993d...,565d7e9f0b7675ee7a7efa56447470fce66fe7529c77c9...,514e66f0e4a78921c67a3b54ce73d2073d659a9aadb48b...,100.0,284.40,989.28,839.64,68.76,0.0,0.00,0,0,LIMA,LIMA,JESUS MARIA,150113
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222868,20250424,2023,9b8311ab65450d9d3913cdeddcfe1ccf053b203d6b7f4f...,cdfdd14e319de906f61c5f68046ba7c6df571f73d59b2c...,51d8e6fcfef5e57957f2183f0fd1087fc37f726a87da64...,100.0,273.00,321.00,120.72,20.28,0.0,52.32,0.0,0,LIMA,LIMA,JESUS MARIA,150113
222869,20250424,2023,066f56a4ba1b0f94bbb4deb092efc27384759337dccce1...,e850aafd6b661ce713c26b5b930a17340665db16529b45...,9a283b1c77e825ae9e749395e2211e9a7dc13721576fe5...,100.0,296.16,321.00,1.44,3.6,0.0,0.00,0.0,0,LIMA,LIMA,JESUS MARIA,150113
222870,20250424,2023,c3edb578cfde39bc9028bb6d95f2ac75390de3a1108d59...,59ea13cb2d62126e29666f7d22652b0f6d249eba6d4e0c...,69fb815dc8767ab941dbbb2d47a06ee67e6f4462318d67...,100.0,298.80,321.00,80.28,7.8,0.0,52.32,0.0,0,LIMA,LIMA,JESUS MARIA,150113
222871,20250424,2023,15c7a113b18551acbd5f0e9a5994611cabc62623195b7e...,2eeda311dbacce523444b0988b8b7a135511a064414dea...,d82371c93a310a6373f10e356508d7f8289a1aca0f4484...,100.0,296.16,321.00,120.72,35.04,0.0,52.32,0.0,0,LIMA,LIMA,JESUS MARIA,150113
222873,20250424,2023,1617b55744917032e13bd0776876f0bba617565262e397...,932216c48163734bd4c16221b80602e8adcc386422bf65...,65ffb0938dd2589293360b12dda5197b875c6883790bff...,12.5,296.16,886.20,137.64,128.88,0.0,144.96,0.0,0,LIMA,LIMA,JESUS MARIA,150113

#7. Agrupamiento

In [ ]:
dataset_arbitrios_jm.groupby('PERIODO').MONTO_SERENAZGO.sum()

PERIODO
2023    24440157.84
2024    26232272.82
2025    27835182.83
Name: MONTO_SERENAZGO, dtype: float64

In [ ]:
dataset_arbitrios_jm.groupby('PERIODO').agg({'MONTO_SERENAZGO': 'sum', 'MONTO_PARQUE_JARDIN': 'mean'})

         MONTO_SERENAZGO  MONTO_PARQUE_JARDIN
PERIODO
2023         24440157.84           168.070900
2024         26232272.82           170.146964
2025         27835182.83           150.855189

In [ ]:
dataset_arbitrios_jm.groupby('PERIODO').agg(MTO_TOTAL_SERENAZGO=('MONTO_SERENAZGO', 'sum'),
                                            MTO_PROMEDIO_PARQUE_JARDIN=('MONTO_PARQUE_JARDIN', 'mean'))

         MTO_TOTAL_SERENAZGO  MTO_PROMEDIO_PARQUE_JARDIN
PERIODO
2023             24440157.84                  168.070900
2024             26232272.82                  170.146964
2025             27835182.83                  150.855189

In [ ]:
dataset_arbitrios_jm.groupby(by=['PERIODO'], as_index=False).agg(MTO_TOTAL_SERENAZGO=('MONTO_SERENAZGO', 'sum'),
                                            MTO_PROMEDIO_PARQUE_JARDIN=('MONTO_PARQUE_JARDIN', 'mean'))

   PERIODO  MTO_TOTAL_SERENAZGO  MTO_PROMEDIO_PARQUE_JARDIN
0     2023          24440157.84                  168.070900
1     2024          26232272.82                  170.146964
2     2025          27835182.83                  150.855189